### ISSUE TITLE
[BUG] - Cannot connect to cluster with special characters in password

### ISSUE THREAD

**Issue by asdfII** [cars10/elasticvue#10]
**Description**
1. It works on single elastic with no x-pack, no username and password.
Like this: http://10.112.17.82:9201/
2. It doesn't work on elastic cluster with x-pack, and using correct username and password.
Like this: http://elastic:urlencode_password@10.112.17.82:9201/
NOTICE: But It works with chrome extension Elasticsearch Head!

**Steps To Reproduce**
Anytime

**Screenshots**
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/4301280/69393269-ad39af80-0d13-11ea-9b27-40dbd913958a.png">

**Environment**
OS: Ubuntu 16.04
Browser: Firefox 70.0.1
Elaticsearch: 6.8.4 (x-pack on)
Elasticvue: 0.16.0
Running Mode: firefox add-ons
Important Elasticsearch Settings: 
  http.cors.enabled: true
  http.cors.allow-origin: "*"
  http.cors.allow-headers: X-Requested-With,Content-Type,Content-Length,Authorization
  xpack.security.enabled: true
  xpack.security.transport.ssl.enabled: true
  xpack.security.transport.ssl.verification_mode: certificate
  xpack.security.transport.ssl.keystore.path: certs/elastic-certificates.p12
  xpack.security.transport.ssl.truststore.path: certs/elastic-certificates.p12

**Comment by cars10** [comment]
Hi, thank you for reporting this bug. Sadly i cannot reproduce the issue, even with the exact same config that you provided. Do you see any error messages in the browser console (press F12, then select the "console" tab) when you try to connect to your cluster?

**Comment by asdfII** [comment]
Sorry for my late.
Here is my test screen with devtools.
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/4301280/69630638-1741b400-1088-11ea-91ff-79a9d3e6c4ff.png">

And the error message is below,
{"error":{"root_cause":[{"type":"security_exception","reason":"failed to authenticate user [elastic]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"failed to authenticate user [elastic]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}

So It seems like authentication doesn't work.

But it works under chrome extension elasticsearch head,
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/4301280/69631159-8f0fde80-1088-11ea-9558-4cf5bdf1fbf3.png">

So strange.

**Comment by cars10** [comment]
Hm, thx for the update. To you have any special characters in your password? That might be the issue, i will check that.

**Comment by cars10** [comment]
Seems that special characters don't work, thanks again for noting this. I already fixed it on develop and will release a new version in the following days. You can always build elasticvue yourself manually or via docker to use the latest version.

**Comment by asdfII** [comment]
Yes, my password contains '#', so I've tried to use '%23' instead but the same error.
Looking forward to the latest version, and thanks a lot for your kind help.

**Comment by cars10** [comment]
Hey @asdfII , just letting you know that i published a new version (0.16.1) that will hopefully fix the issue. You can update the firefox addon manually or wait for it to update automatically, either way you should be able to connect to your cluster. You also do not need to escape the password, you can enter is as-is.
