### ISSUE TITLE
[FEAT] Electron App

### ISSUE THREAD

**Issue by KMayne** [cars10/elasticvue#101]
**Description**
It would be great if this app existed as an Electron app. That way we could avoid having to allow CORS access and running a container just for elasticvue.

**The feature is similar to..**
The Facebook Messenger desktop app.

**Additional context**
N/A

**Comment by jtsunne** [comment]
Yes, it will be very useful, coz I'm using Edge only for your Extention (my main browser is Safari)

**Comment by cars10** [comment]
Okay you guys persuaded me, i am working on a desktop app :)

Although it won't be based on electron, i am currently looking into [tauri](https://tauri.studio/).

**Comment by jtsunne** [comment]
@cars10 I can help if you wish

**Comment by cars10** [comment]
I have published the first beta build for a desktop app of elasticvue. Please report any issues, especially on mac and windows.

[Link](https://github.com/cars10/elasticvue/releases/tag/elasticvue-desktop-v0.40.1)

Feel free to test it :)

**Comment by cars10** [comment]
Closed in favor of #105 105
