### ISSUE TITLE
[BUG] - Chrome plugin cannot connect to my ES cluster (on docker)

### ISSUE THREAD

**Issue by variable** [cars10/elasticvue#102]
**Description**
Cannot chrome plugin connect to my ES cluster (on docker)

**Steps To Reproduce**
1. I have setup the ES cluster according to this [link](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-compose-file) using docker compose
2. Added the following to environment subsection 
```
      - http.cors.enabled=true
      - http.cors.allow-origin="http://localhost:8080"
      - http.cors.allow-headers="X-Requested-With,Content-Type,Content-Length,Authorization"
```
3. Run `docker-compose up -d`
4. Verified in browser `https://localhost:9200`, put in username and password
5. Open up elasticvue chrome extension, enter the connection details and username and password

**Screenshots**
![image](https://user-images.githubusercontent.com/558175/166168475-d4a045c6-f3d5-4bc2-8ad0-2f7d2f829419.png)
![image](https://user-images.githubusercontent.com/558175/166168491-18220945-ed52-4c95-b43a-8f726b7aa302.png)
![image](https://user-images.githubusercontent.com/558175/166168510-70e594a8-0691-420a-a56b-d808e2586971.png)

~~Seems username+password are not being sent in headers?~~

**Environment (please include the following information):**
* Elasticsearch version: v8
* Operating system: Mac OSX
* Browser + version: Chrome Version 100.0.4896.127
* Elasticvue version: 0.40.0
* How are you running elasticvue? (docker, browser extension, web app): browser extension

**Comment by cars10** [comment]
Hey, thanks for using elasticvue! As you are using elasticsearch 8: did you Import the certificate or are you using a trusted CA? If not, please check-out https://github.com/cars10/elasticvue/wiki/Elasticsearch-8

**Comment by variable** [comment]
Pretty sure I have done option 2, also made chrome to trust localhost certs

![image](https://user-images.githubusercontent.com/558175/166325791-751f8785-79ea-4167-b92c-e77da3f0532e.png)

**Comment by variable** [comment]
I also tried the simprox approach

![image](https://user-images.githubusercontent.com/558175/166334463-61d3259a-78c0-40c5-bbb9-13f760b4b3a1.png)

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/558175/166334490-78e38bb4-cec8-48fa-83d9-f0f2f89bbbd8.png">

**Comment by variable** [comment]
Using postman to verify "POST" method works

![image](https://user-images.githubusercontent.com/558175/166335397-9a751821-944a-4633-8ca7-bd067459286e.png)

**Comment by variable** [comment]
this is my docker-compse file
```
version: "2.2"

services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
    user: "0"
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_PASSWORD} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: es01\n"\
          "    dns:\n"\
          "      - es01\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: es02\n"\
          "    dns:\n"\
          "      - es02\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: es03\n"\
          "    dns:\n"\
          "      - es03\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        echo "Setting file permissions"
        chown -R root:root config/certs;
        find . -type d -exec chmod 750 \{\} \;;
        find . -type f -exec chmod 640 \{\} \;;
        echo "Waiting for Elasticsearch availability";
        until curl -s --cacert config/certs/ca/ca.crt https://es01:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u elastic:${ELASTIC_PASSWORD} -H "Content-Type: application/json" https://es01:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120

  es01:
    depends_on:
      setup:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es02,es03
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
      - http.cors.enabled=true
      - http.cors.allow-origin="http://localhost:8080"
      - http.cors.allow-headers="X-Requested-With,Content-Type,Content-Length,Authorization"
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  es02:
    depends_on:
      - es01
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata02:/usr/share/elasticsearch/data
    environment:
      - node.name=es02
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es02/es02.key
      - xpack.security.http.ssl.certificate=certs/es02/es02.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es02/es02.key
      - xpack.security.transport.ssl.certificate=certs/es02/es02.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
      - http.cors.enabled=true
      - http.cors.allow-origin="http://localhost:8080"
      - http.cors.allow-headers="X-Requested-With,Content-Type,Content-Length,Authorization"
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  es03:
    depends_on:
      - es02
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata03:/usr/share/elasticsearch/data
    environment:
      - node.name=es03
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es03/es03.key
      - xpack.security.http.ssl.certificate=certs/es03/es03.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es03/es03.key
      - xpack.security.transport.ssl.certificate=certs/es03/es03.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
      - http.cors.enabled=true
      - http.cors.allow-origin="http://localhost:8080"
      - http.cors.allow-headers="X-Requested-With,Content-Type,Content-Length,Authorization"
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      es03:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
    mem_limit: ${MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  certs:
    driver: local
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local
  kibanadata:
    driver: local
```

**Comment by variable** [comment]
With firefox addon

It says "Either your cluster is not reachable or you did not configure CORS correctly. " which the chrome extension doesn't.

![image](https://user-images.githubusercontent.com/558175/166340040-bf13626e-f415-4207-8043-8eb5931cf58b.png)

**Comment by variable** [comment]
OK.... I managed to make it work, by changing the cors from 
`http.cors.allow-origin=http://localhost:8080` 
to
`http.cors.allow-origin=/.*/`

**Comment by tbigby-kristin** [comment]
I'm getting the same issue on an Elasticsearch 6.8.15 localhost with no SSL, on both Firefox and Chrome browser extensions. The '_search' request returns a 403 Forbidden but the 'localhost' request works fine.

I tried in Firefox Network debugger to 'Edit and Resend' and change headers until the '_search' request succeeded. It is the 'Origin' header that causes the 403 error, with no Origin the request is successful.

My Firefox shows an Origin header of:
`Origin: moz-extension://7d95634b-71e4-494e-b885-1c673f8bf2da`

And Chrome:
`chrome-extension://hkedbapjpblbodpgbajblpnlpenaebaa`

I even tried older versions back to 0.37.0 in Firefox and encountered the same issue, so perhaps there has been a browser update?

Thanks @variable for the `allow-origin` line to use, unfortunately my Elasticsearch is embedded in another product and I can't currently find the config file for it!

**Comment by cars10** [comment]
Did you guys restrict the extension permissions in some way? When using the browser extensions you do not need to configure CORS because they bypass CORS via the "Read and change all your data on the website you visit" (chrome) and "Access your data for all websites" (firefox) permission.

In any way, please include a screenshot of the browser console, thanks :)

**Comment by variable** [comment]
![image](https://user-images.githubusercontent.com/558175/166559375-6562cd5e-55c7-49ba-bb45-a72fd9544d72.png)

**Comment by tbigby-kristin** [comment]
@cars10 - I didn't restrict the permissions knowingly :) I do have 'Enhanced Tracking Protection' on in Firefox but tried turning it off too and still the same result. Also tried 'Run in Private Windows' but no go. It's an odd one!

Some screenshots:

![image](https://user-images.githubusercontent.com/16282833/166571987-c7757ec1-b15c-4db0-81eb-acc1a458ef63.png)

![image](https://user-images.githubusercontent.com/16282833/166572004-9dbcae60-7789-4cb8-8c14-d80c03c8f749.png)

![image](https://user-images.githubusercontent.com/16282833/166572823-5603bdfd-ed29-4d2d-b29a-26de1b9d2e67.png)

Console - Errors only
![image](https://user-images.githubusercontent.com/16282833/166572028-e93882cc-1a78-4d66-b9f3-6a2337c516e6.png)

Console - Warnings... has lots of unrelated cookie warnings only
![image](https://user-images.githubusercontent.com/16282833/166572105-25b0f6cc-9654-4cc1-829d-0b1bc85cc5b2.png)

**Comment by cars10** [comment]
Thanks! Nothing unusual there.. Do you login with an elasticsearch user that has enough permissions? Can you use the exact same credentials to curl the `_search` endpoint?

**Comment by CrazyOptimist** [comment]
> OK.... I managed to make it work, by changing the cors from `http.cors.allow-origin=http://localhost:8080` to `http.cors.allow-origin=/.*/`

Still doesn't work for me. I used docker for `elasticvue` and followed option 2 for generating/importing certificates.

```yaml
version: "3.9"
services:
  elasticvue:
    container_name: elasticvue
    image: cars10/elasticvue
    ports:
      - 8080:8080
    restart: "unless-stopped"
```

**Comment by cars10** [comment]
> > OK.... I managed to make it work, by changing the cors from `http.cors.allow-origin=http://localhost:8080` to `http.cors.allow-origin=/.*/`
> 
> Still doesn't work for me. I used docker for `elasticvue` and followed option 2 for generating/importing certificates.
> 
> ```yaml
> version: "3.9"
> services:
>   elasticvue:
>     container_name: elasticvue
>     image: cars10/elasticvue
>     ports:
>       - 8080:8080
>     restart: "unless-stopped"
> ```

How exactly to you run elasticsearch? This for example works perfectly:

```
docker run -e "http.cors.enabled=true" \
           -e "http.cors.allow-origin=/.*/" \ 
           -e "discovery.type=single-node" \
           -p 9200:9200 \
           -p 9300:9300 \
           docker.elastic.co/elasticsearch/elasticsearch:7.8.0

```

**Comment by CrazyOptimist** [comment]
Here's my docker-compose file

```yaml
version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.1.3
    container_name: es
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - http.cors.enabled=true
      - http.cors.allow-origin="/.*/"
      - http.cors.allow-credentials=true
      - http.cors.allow-headers="X-Requested-With, Content-Type, Content-Length, Authorization"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    restart: always

volumes:
  es_data:
```

**Comment by cars10** [comment]
Okay there are a few things missing here.

a) Please try to change the CORS setting like this (removing the quotes):

```
      - http.cors.allow-origin=/.*/
```


b ) Please checkout the [official docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-compose-file) for running elasticsearch 8 with docker-compose. Your current issue is that you do not have a volume for the certificates (`/usr/share/elasticsearch/config/certs`) so elasticsearch will generate a new ssl certificate each time you restart your cluster. So importing the certificate only last for the current run.

**Comment by tbigby-kristin** [comment]
> Thanks! Nothing unusual there.. Do you login with an elasticsearch user that has enough permissions? Can you use the exact same credentials to curl the _search endpoint?

Apologies, have gotten busy over the last few days on other things.

If I run:

`curl -X GET -D - "localhost:9200/_search?pretty"`

I get the responses successfully. But if I run:

`curl -X GET -H "Origin: moz-extension://12345/" -D - "localhost:9200/_search?pretty"`

I get `HTTP/1.1 403 Forbidden`.

So proving it is not liking having the `Origin` header in the query.

However I've come to suspect that my localhost Elasticsearch config might have some non-default CORS settings, due to the way it is embedded through Java or something, so I don't think it is a good example for a bug. Unfortunately I still can't find a config for it so I assume it uses some Java properties for configuration instead, which could be non-default.

I was able to connect successfully to a remote Elasticsearch cluster on another server, with a more standard configuration. So probably best to close off my comments in this ticket as an Elasticsearch server config issue.

Thank you very much for your responses anyway!
