### ISSUE TITLE
[FEAT] Show _score in search results

### ISSUE THREAD

**Issue by horkyada** [cars10/elasticvue#104]
**Description**
I would like to see elastic's _score while playing with searching.

**Additional context**
I don't know if it is a feature or bug, but I cannot see the _score in the filters either. When I download the JSON, the _score is there. 
![image](https://user-images.githubusercontent.com/25367592/171364819-eca490f1-ffba-4626-b9fc-aa796ef65d2b.png)

Firefox (99.0.1 (64-bit)) extension (0.40.1)

**Comment by cars10** [comment]
fixed in `0.42.0`
