### ISSUE TITLE
Desktop app beta testing

### ISSUE THREAD

**Issue by cars10** [cars10/elasticvue#105]
I have published the ~~first~~ ~~second~~ third beta build for a desktop app of elasticvue. Please use this issue to report any problems, especially on mac and windows.

[Link](https://github.com/cars10/elasticvue/releases/)

Last update: 07.11.22, Elasticvue 0.43.0

### Known issues
* the builds are not signed yet so you might get some security warnings from your os during installation

#### Linux
* the app does not scale correctly when changing the display resolution scaling with xrandrs `--scale` option

#### Mac
* build for apple silicon / m1 / arm: you have to run `xattr -c elasticvue.app` after installation to make it work
* ~copy/paste does not work~ Should be fixed with `0.43.0`
* backup import does not work

#### Windows
* ~windows defender reports a trojan for the .msi installer, [see this](https://github.com/tauri-apps/tauri/issues?q=trojan)~ Should be fixed
* the page does not reload automatically after importing a backup. You have to manually right click -> reload

**Comment by nofak** [comment]
Hi, I have downloaded beta2 version: elasticvue_0.40.1_macos_aarch64 but it is not working for me, it is Apple M1 Pro:
<img width="292" alt="Screenshot 2022-06-13 at 10 07 13" src="https://user-images.githubusercontent.com/1303361/173308667-24466af2-baf3-4ae6-8793-b4a575f2785d.png">

**Comment by cars10** [comment]
Hey, thanks for testing! I don't own a mac and can't test this on my own. Are you able to compile elasticvue locally to test it this resolves the issue ([rust](https://rustup.rs/) and [tauri](https://tauri.studio/v1/guides/getting-started/prerequisites/) required)?

**Comment by nofak** [comment]
We can try, could you please provide instructions on how to build? in the readme is yarn install, but this is not working in the branch elasticvue-desktop-v0.40.1.

I have xcode, rustc 1.61.0, sources from git - tag elasticvue-desktop-v0.40.1

What is the next step? I can try to build it locally, but I need more steps on how to do it, thanks a lot.

**Comment by cars10** [comment]
Please try the following steps:

1. check node version, use node 16 if possible
2. switch branch `git checkout tauri`
3. install yarn dependencies without optionals `yarn install --ignore-optional`
4. try to build tauri `yarn tauri build`

thanks!

**Comment by cars10** [comment]
Are you sure you are using the correct git branch in elasticvue? `yarn tauri build` should be available :) please make sure that you did `git checkout tauri` after cloning elasticvue

**Comment by nofak** [comment]
yes I'm on the tauri branch, as you can see in the commandline, the green tauri means git branch :-)
I tried to run the 'yarn delete tauri' and then 'yarn tauri build' works :-)
![Screenshot 2022-06-13 at 20 46 25](https://user-images.githubusercontent.com/1303361/173423739-45445da4-f289-4875-8f4f-071df9cb5913.png)

![Screenshot 2022-06-13 at 20 52 13](https://user-images.githubusercontent.com/1303361/173424278-6c94dfef-b209-46f5-9fc4-570632a5a593.png)


So there is dmg file (cannot upload it directly so it is part of zip):
[elasticvue_0.40.1_aarch64.dmg.zip](https://github.com/cars10/elasticvue/files/8893666/elasticvue_0.40.1_aarch64.dmg.zip)

**Comment by kdambekalns** [comment]
That build seems broken, too (M1 Max, macOS 12.4). 😞

**Comment by kdambekalns** [comment]
> In the meantime you can probably use the build made by @nofak

That's the build I meant… it's broken, too. So I tried to build, and ran into

```
$ yarn tauri build
yarn run v1.22.19
error Command "tauri" not found.
```

So I did run `yarn upgrade` and then magically it kind of worked:

```
$ yarn tauri build
yarn run v1.22.19
$ /Users/karsten/Projects/elasticvue/node_modules/.bin/tauri build
     Running beforeBuildCommand `npx cross-env VUE_APP_DESKTOP_BUILD=true yarn build`
$ rm -rf dist && vue-cli-service build

⠋  Building for production...
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

// TONS of such notices


  File                                              Size                                                             Gzipped

  dist/assets/js/chunk-vendors.2bdb13e3.js          939.85 KiB                                                       284.86 KiB
  dist/assets/js/app.e5d78626.js                    248.65 KiB                                                       63.00 KiB
  dist/assets/js/FilterWorker.01862603.worker.js    28.11 KiB                                                        10.27 KiB
  dist/assets/css/chunk-vendors.6158664e.css        700.01 KiB                                                       97.33 KiB
  dist/assets/css/app.95387835.css                  8.19 KiB                                                         2.37 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html

Error running CLI: failed to build app: No such file or directory (os error 2)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

🤷‍♂️

**Comment by cars10** [comment]
Weird, I have added a `yarn tauri:build` command that should work. Do you have rust installed and tauri setup? Without these you will not be able to build the desktop app.

**Comment by kdambekalns** [comment]
Ah, right! `brew install rust` and `yarn add -D @tauri-apps/cli` did help. I would have thought the latter is already part of the setup… Still no success:

`error: package 'app v0.1.0 (/Users/karsten/Projects/elasticvue/src-tauri)' cannot be built because it requires rustc 1.60 or newer, while the currently active rustc version is 1.59.0`

So I did ´brew uninstall rust` and `curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh` (😨) and it worked.

[elasticvue_0.40.1_x64.dmg.zip](https://github.com/cars10/elasticvue/files/8946852/elasticvue_0.40.1_x64.dmg.zip)

**Comment by kdambekalns** [comment]
Two observations:

1. You cannot import settings until you have connected to a cluster (the main menu is not available before that.)
2. Then you can use the import, but it doesn't do anything - no saved clusters are available afterwards, even though there is no error message.

**Comment by cars10** [comment]
Hey, thanks for testing!

1. This is not a bug (planned for a future release)
2. Do the clusters show up if you restart the app?

**Comment by kdambekalns** [comment]
Nope, even after a restart the clusters don't show up.

**Comment by cars10** [comment]
Alright, thanks! Does file access work at all on mac? Can you download a backup (or a search/rest result)?

**Comment by nofak** [comment]
Houston, we have a problem :-D

Build elasticvue_0.40.1_x64.dmg.zip from Karsten is not working for me:
<img width="292" alt="Screenshot 2022-06-23 at 11 13 22" src="https://user-images.githubusercontent.com/1303361/175263350-21c64f5f-33d3-45df-b637-3a47f683d2d8.png">

but my buildelasticvue_0.40.1_aarch64.dmg.zip is working for me, but not for @kdambekalns  :-D

I have Mac 12.4, Apple M1 Pro

**Comment by cars10** [comment]
Could this be related to security issues due to missing signing? Can you get any more details/errors on macos, maybe this is some kind of "trust insecure apps" stuff like on windows?

**Comment by kdambekalns** [comment]
That would (usually) be a different message. macOS would tell you it cannot open the application, and you can then open it using the context menu in the Finder and confirm you want to open it.

_This_ message says it's "damaged" immediately. 🙄

**Comment by kdambekalns** [comment]
`xattr -cr elasticvue.app` solves it, though… That removes all extended attibutes, in this case only one is present: `com.apple.quarantine`

**Comment by joshzcold** [comment]
The desktop binary has trouble displaying information on my machine
```
docker run -ti -e "http.cors.enabled=true" -e "http.cors.allow-origin=tauri://localhost" --name elasticsearch -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.17.6
```
Im connected, but with no node information

https://user-images.githubusercontent.com/36175703/188752813-4d39fc3f-bec0-44dc-8c0a-b46b91c0ce72.mp4

**Comment by Numline1** [comment]
Hey guys, there's couple of strange bugs in the desktop app on macOS - the copy/paste problem is already reported, but Cmd + Q gets blocked in all other apps. Sometimes, rather than blocking other apps, I can switch focus into another window and when I press Cmd + Q, elasticvue quits (instead of the app that's focused).

The other (purely visual) issue is the icon in the docks, that's slightly disproportional to other apps (see image).

![image](https://user-images.githubusercontent.com/12192684/194139284-27780e5a-80e1-4b8b-aca6-6d4fc07bbde6.png)

Other than that, pretty good job on the desktop version, thank you!

**Comment by cars10** [comment]
Hey @Numline1 , thanks for the feedback! Mac and windows feedback is particularly important because i only use linux systems. I will look into this for the next release.

**Comment by bengaywins** [comment]
@cars10 Not sure if this is a problem for anyone else, but the FireFox extension shows data but the desktop app does not. Both are the latest. Is there some known issue about this? The app seems to run okay.

**Comment by cars10** [comment]
Hey @bengaywins , which version are you using and what os?

**Comment by bengaywins** [comment]
The extension is `Elasticvue 0.43.0` and the desktop app is `Version 0.43.0 (20221106.104749)`.

**Comment by Eddcapone** [comment]
[v0.44.0](https://github.com/cars10/elasticvue/releases/tag/v0.44.0) Does not work on windows 10. Test Connection was successfull, but nothing is loading.

**Comment by cars10** [comment]
Thank you all for testing the desktop app. I have release a new version that should fix all of your issues, feel free to try it out :) https://github.com/cars10/elasticvue/releases/tag/v1.0.0-beta-1

**Comment by maurin-at-homiwoo** [comment]
Hi @cars10 
Thanks for your work on that, that really cool :). 
I was wondering how we should report bug for the desktop app (or for the beta 1, not sure if the bug is related to the new vue3 version or the desktop). 
When going to rest tab I don't have the area to type the request if I'm connect to an es2 cluster (it's working perfectly with an es8 cluster). 

Es2 Cluster : 
![image](https://github.com/cars10/elasticvue/assets/96076076/915fc9ed-464c-4595-be38-6feab5922d0d)

Es8 Cluster : 
![image](https://github.com/cars10/elasticvue/assets/96076076/72430f01-e23a-4c9d-a7ab-4eb6e6ce9814)

Thanks !

**Comment by cars10** [comment]
Hey @maurin-at-homiwoo , thanks for testing the beta :) Elasticvue officially supports elasticsearch 6, 7 and 8. Elasticsearch 2 was EOL in february 2018 - **more then five years ago**. I currently do not have the time to test and support versions that are not even supported by elastic. I really recommend to update your cluster because this is a huge security risk, but i understand if that is not possible for your product right now.

**Comment by axlroden** [comment]
![Screenshot 2023-08-25 at 10 46 59](https://github.com/cars10/elasticvue/assets/4016762/71e12897-a369-4baf-abd2-126925e99eea)
We have over 3000 shards in our cluster, the shards tab is kinda... not ideal :)
Maybe the nodes should be listed on top and shards going down?

**Comment by cars10** [comment]
I guess that depends on your use case. What do you try to achieve when viewing your shards?

**Comment by marcinjahn** [comment]
I'm testing beta-5 on Linux (AppImage).
The app launches and works fine, until it freezes. And it freezes pretty much on every run. Sometimes it happens after about a minute, sometimes sooner or later. There isn't any specific action that I'm doing. I could just leave the app running in the backround, without any pending action, and when I get back to it, it's frozen.

I run it from terminal, I noticed this warning after the app froze:

```
** (elasticvue:619830): WARNING **: 13:02:30.926: atk-bridge: get_device_events_reply: unknown signature
```

Not user if this is related with the freezes, but it definitely could be.

Btw, I hope flatpak will come as an option later on? :)

**Comment by cars10** [comment]
Hm, thats weird..  Thanks for reporting! Do you notice a spike in ram or cpu usage before the crash happens?

**Comment by marcinjahn** [comment]
I don't see any spike, but I noticed there're lots of elasticvue processes (I launched it just once):

![image](https://github.com/cars10/elasticvue/assets/10273406/0c90e988-248d-4a48-bc46-4d8b248f1446)

Is it normal?

**Comment by cars10** [comment]
Yea, the amount of subprocesses should be normal, these are handled by tauri. Would it be possible for you to test the binary and see if your issue persists? [binary](https://github.com/cars10/elasticvue/releases/download/v1.0.0-beta-5/elasticvue)

**Comment by bfontaine** [comment]
I’ve been using beta2 for some time and today I got an issue with a frozen UI, so I upgraded to beta5 but I still have the same issue. I’m on Ubuntu 23.04, using the `.deb` installation. On some indices (not all) from a remote 7.16.3 server, when I click on the index it starts to load the documents, then becomes unresponsive after a couple seconds, then after 10-15s it stops trying to load the documents and says it couldn’t find any. There is probably something wrong with my indices given that the issue has not always been present, but it’s not normal that Elasticvue freezes.
Where can I see some logs to understand what goes wrong?

**Comment by pWoLiAn** [comment]
![image](https://github.com/cars10/elasticvue/assets/49567139/2eaa2a9d-1671-4ed9-a7df-19f00d9025ce)
filter doesnt work on indices page for beta-5 build

**Comment by marcinjahn** [comment]
Regarding the issue I submitted about UI freezing - beta6 did not resolve that.

**Comment by cars10** [comment]
Desktop app stable `1.0` is released so this issue is closed. Thank you all for testing!
<https://github.com/cars10/elasticvue/releases/tag/v1.0.0>
