### ISSUE TITLE
Improved rendering of embreded json

### ISSUE THREAD

**Issue by tdsrhh** [cars10/elasticvue#107]
Dears sirs

Please see the attached image. I have data where the message field contains dynamic data formatted as json. It would be great if this is rendered better so it's easier to view...

<img width="706" alt="Capture" src="https://user-images.githubusercontent.com/40692620/175805353-52ed8c1a-b58a-4d2b-ab1f-eeae0e9bdf0d.PNG">

Regards

**Comment by cars10** [comment]
Hey, thanks for using elasticvue :) 

Sadly i doubt that this is possible. In your example the type of the value is a string (that contains a stringified json, yes), but elasticvue has no way of knowing what kind of data a string contains. Is there a specific reason why you store json data as string anyway? This also severely limits your searching and filtering capabilities.

**Comment by tdsrhh** [comment]
Hi

Thanks for your reply. I use Elasticsearch through a serilog sink adapter and the template is auto registered (AutoRegisterTemplateVersion = ev7) . We have a lot of dynamic data so to define a custom ‘standard’ template in our logs seems very hard …

This is the reason that we use it this way. And yes, we know this limits your searching and filtering capabilities …

Regards

**Comment by cars10** [comment]
Thanks for getting back :) In this case i would use the elasticsearch json processor pipeline to automatically parse the stringified json and make it searchable: https://www.elastic.co/guide/en/elasticsearch/reference/current/json-processor.html
