### ISSUE TITLE
Host connection ignoring passed port, using default port (9200) instead

### ISSUE THREAD

**Issue by fernandomonje** [cars10/elasticvue#11]
Hello, I'm a frequent user of elasticvue web interface (https://app.elasticvue.com/) and today I've noticed that I cannot connect to my elastic database.
I've checked the network log from google Chrome and found that the web application is ignoring the port that I'm using in the host URL.
Here are some evidences of the problem.
![network_error](https://user-images.githubusercontent.com/32906993/69829067-47f72a00-11fd-11ea-87e2-a42b6fe1db56.png)
![elastic_url](https://user-images.githubusercontent.com/32906993/69829068-47f72a00-11fd-11ea-8022-e94288c4643b.png)

**Comment by cars10** [comment]
Hi, thanks for noting this. I can reproduce the issue and will fix it ASAP. Sorry for the inconvenience!

**Comment by cars10** [comment]
Hi, i just release a new version `0.16.2` that should fix the issue. Please let me know if you encounter any other problems.

**Comment by fernandomonje** [comment]
It's working now, thank you!
