### ISSUE TITLE
[BUG] - Sending REST queries with GET leads to an elasticsearch exception mirrors #26

### ISSUE THREAD

**Issue by cemeyer2** [cars10/elasticvue#113]
detail is in #26 

But looks like the fix implemented there broke old ES versions with elasticvue. At least es5 and es6 are impacted

**Comment by cars10** [comment]
I cannot reproduce this, can you please give me more details on this? Elasticsearch has supported POST for requests like search for a very long time. A 403 forbidden might also be related to your environment and not elasticsearch itself.
![image](https://user-images.githubusercontent.com/4118628/185853520-60ad1032-64b5-4ae7-b81d-96c6960e7847.png)
![image](https://user-images.githubusercontent.com/4118628/185853540-8c38bb46-c067-4d53-b831-043ee57d68e4.png)

Tested with the official docker image:

`docker run --rm --name elasticsearch -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:5.6.16`

**Comment by cars10** [comment]
Closed due to lack of activity. Please re-open with more information if you can reproduce this.
