### ISSUE TITLE
[BUG] - REST tab network error when data recieved

### ISSUE THREAD

**Issue by Purecoder** [cars10/elasticvue#114]
Hi,

In Rest menu i use with _search query and i seen recieved data in developer network tab but add on throw network error result.

1. Open elasticvue with firefox
2. Click on the STEP tab
3. index_name\_search with post

**Screenshots**
<img width="696" alt="Untitled" src="https://user-images.githubusercontent.com/10616137/187903083-ef849a7b-1cfb-4c25-b9e0-a067261d3dc4.png">

"version" : {
    "number" : "7.4.2",
    "build_flavor" : "default",
    "build_type" : "rpm",
    "build_hash" : "2f90bbf7b93631e52bafb59b3b049cb44ec25e96",
    "build_date" : "2019-10-28T20:40:44.881551Z",
    "build_snapshot" : false,
    "lucene_version" : "8.2.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },

Firefox 104.0.1 Windows 10 Pro
Elasticvue version latest

before  i write this post i was restart pc and i tryied its work. Maybe sometimes error idk

**Comment by cars10** [comment]
Hey, sorry that you have issues with elasticvue. Can you please add a screenshot of the browser console if this happens again? Thanks!

**Comment by cars10** [comment]
Closed due to lack of information, please re-open if is happens again

**Comment by itsx** [comment]
I probably experienced the same issue in Chromium using the REST tab.The complete browser restart helped.

Version 109.0.5414.119 (Official Build) snap (64-bit)
