### ISSUE TITLE
How to debug connection issue to ES 8.4.1.1

### ISSUE THREAD

**Issue by kibble1** [cars10/elasticvue#115]
Looking for any help with debugging a connection issue to ES 8.4.1.1 with Security disabled, connection worked fine prior to updating to 8.4.1.1 from 8.2.x.

Security is disabled (it is a dev environment with no public access).

curl http://ESdev.blah.net:9200 works fine from a workstation on the same network.

Does elasticvue produce any logs that might help debuging?

**Comment by cars10** [comment]
Hey i have added some documentation on this, please check [Debugging connection issues](https://github.com/cars10/elasticvue/wiki/Debugging-connection-issues) and report back. 
Also elasticvue logs errors to the browser console so you can check that. How are you using elasticvue? (browser extension, web app, docker, desktop app, ..)

**Comment by kibble1** [comment]
Forgot to mention that I was using the Chrome extension.

I forgot about using the browser to check, thanks for that hint, turns out that I for got to set the initial master node.

The info you added in the Debugging Connection Issues is spot on and very helpful. Can you add to it to try http://localhost:9200/_cluster/health elasticvue won't connect if cluster health isn't green.

I fixed my initial master problem and elasticvue connected. :)
