### ISSUE TITLE
[BUG] - In custom search query commenting parts of query leads to invalid query

### ISSUE THREAD

**Issue by ivanmarjanovic** [cars10/elasticvue#117]
**Description**
When using comments in custom search query text is commented on the shortcut and colored properly but on execution.
I can just presume the issue is that comments are not stripped before execution so the text entered is invalid JSON. This is very easy to do and there is plenty of libraries.  Also, it would be nice to get some indication is JSON for query invalid or if the search request failed and with which message was returned. 

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Click on Search Tab
2. Click on a custom search query
3. Enter a valid search query and execute => it works
4. Use Ctrl - / to comment out part of a search query that is ... optional
5. Execute again and you will receive a message Invalid search query 

![image](https://user-images.githubusercontent.com/40989450/190110744-25e06606-278c-4188-99be-3e229c09a6b5.png)

**Environment (please include the following information):**
* Elasticsearch version: 7.14
* Operating system: Linux Ubuntu 22.04
* Browser + version: Chrome 105.0.5195.102
* Elasticvue version: Elasticvue 0.42.0
* How are you running elasticvue? browser extension

**Comment by cars10** [comment]
Hey, thanks for using elasticvue. I do see that his is annoying, but i currently already use a custom json parser library so i am not sure if this is possible. I will look into it though.

**Comment by cars10** [comment]
Will be fixed in the currently ongoing quasar rewrite :)

**Comment by cars10** [comment]
Fixed in 1.0.0-beta-1
