### ISSUE TITLE
Customize ElasticVue - offer only search to end users

### ISSUE THREAD

**Issue by LYDE1234** [cars10/elasticvue#118]
ElasticVue looks like a good alternative to the Discover functionality in OpenSearch Dashboards, but we'd like to customize it so that end users can only use the Search functionality and not see the Admin tools (shards, indices, cluster, etc). How would we do this? is there an existing fork or mod that allows this already, or could you give us a description of how we could implement this ourselves?

**Comment by cars10** [comment]
Do you really care about users not *seeing* anything else, or could this be the same as #67 ?

**Comment by cars10** [comment]
Can you explain what you're trying to offer in more detail please? Right now elasticvue is built for developers that want an easy way to check the data and interact with the cluster. It was not built to provide search for end users, you would typically need way more customization for that.

**Comment by cars10** [comment]
I think you want a "finished" search experience for end users like app search?
https://docs.elastic.co/search-ui/tutorials/app-search
![image](https://user-images.githubusercontent.com/4118628/192967602-0bde628c-604e-4278-8586-9011a1be4f31.png)

**Comment by LYDE1234** [comment]
We'll have to look into App Search, thanks for pointing to that. 

What we want is to give users (developers inside our organisation) an easy way to search for root causes. We run nightly QA jobs on all our products and ingest the log files from the jobs, the log files from the products under test, and the event logs from the test machines. We want to ingest that data into separate indices to give maximum freedom in correlating them, and 
also extend the service to correlate with other data sources, like network metrics. Our challenge is how to present data from multiple indices that are only correlated by timestamp in an easy, user-friendly format. ElasticVue Search looks useful because you can select indices freely and the result data is shown in a table, ordered by time. 

We're a bit challenged on how to give users a good search experience inside ElasticSearch / OpenSearch. Index Patterns cover indices that are similarly named and have similar structure - we want users to search freely across indices whose only shared requirement is a timestamp. As an interim "solution", we have now shoe-horned all the data into a single index but that's not a good design longer term because every new data source will have to be forced into this shared index format, or the format will have to swell to accomodate new data sources, making it kludgy over time.

**Comment by cars10** [comment]
Alright, thanks for the explanation. Maybe an alternative to elasticvue like dejavu better suits your needs? They only offers a search interface.
https://github.com/appbaseio/dejavu

**Comment by cars10** [comment]
I will close this for now because a feature like this is not planned for elasticvue. Feel free to keep the discussion going if the alternatives (custom ui, dejavu, etc) do not fit your usecase :)
