### ISSUE TITLE
[FEAT] Search results as raw json

### ISSUE THREAD

**Issue by igoooor** [cars10/elasticvue#119]
**Description**
It would be great to be able to see the entire response of a Search, and not just the hits.
This would allow us to also check aggregations for example.

The only workaround at the moment is to download the json and open it in a text editor. But when debugging a query and running a lot of queries, it's a bit too long to do it everytime

**Comment by igoooor** [comment]
Probably my lack of knowledge sorry 😅
I need to learn the REST API from ES then I guess. Thanks for the hint I will have a look

**Comment by igoooor** [comment]
Thank you it works!

**Comment by cars10** [comment]
Great :)
