### ISSUE TITLE
[Feature Info] Connect to a remote server

### ISSUE THREAD

**Issue by vivek-kumar-sm** [cars10/elasticvue#12]
How would I connect to a remote server's elastic search with elasticvue?
Please give me a direction if possible.

**Comment by cars10** [comment]
Hi, you can simply enter the address of your server. For example if you use the elastic cloud and your server is reachable via something like `c4c19a32ffa7f8bc45446.europe-west3.gcp.cloud.es.io:443` then you can enter that url in the "host" field and click "connect" to connect to it.

**Comment by vivek-kumar-sm** [comment]
Hi,
Thank you for the response.
Is the port mentioned in your example is the port on which elastic search is configured?

**Comment by cars10** [comment]
Yes, it should be the elasticsearch port.

**Comment by vivek-kumar-sm** [comment]
I am using something like 
`<siteurl>:[elasticsearch_port]`
Should it work like this or I would require the exact IP of the server?

**Comment by cars10** [comment]
You can use both if your server is reachable via both ways. A good test is to see if you can reach it in the browser, for example entering `<siteurl>:[elasticsearch_port]` in the browsers url bar. If you see the default elasticsearch information then you should be able to use that url to connect in elasticvue.

**Comment by vivek-kumar-sm** [comment]
Thank you for your patience and all the information you've provided. I am closing this ticket.

**Comment by cars10** [comment]
Always happy to help :)
