### ISSUE TITLE
[FEAT] Use relative paths

### ISSUE THREAD

**Issue by benoit-scnd** [cars10/elasticvue#120]
This kind of tool should be usable out-of-the-box (docker image) in a sub-directory, for example "/elasticvue/".
Currently we have to rebuild the docker image with the env var VUE_APP_PUBLIC_PATH to do the job.
Furthermore this tool doesn't need to be SSR compliant.

Here is some ideas to resolve this issue:

- For the routes, the hash mode should be used in the router config. (https://router.vuejs.org/guide/essentials/history-mode.html#hash-mode)
- For the assets, the paths should be relative without slash at the start of each of them.

**Comment by cars10** [comment]
This is most likely an issue on the vue side. I will revisit this once i can finally update to vue 3 (**still** waiting for vuetify..) and vue-router 4.

In the meantime you can probably circumvent this with url rewrites in your webserver (e.g. nginx) config.

**Comment by cars10** [comment]
Vue 3 and vue-router 4 still need to be compiled with a concrete path if you want to host to anything other then `/`.
