### ISSUE TITLE
[ENHANCE] Need UI Enhancement for any refresh events.

### ISSUE THREAD

**Issue by deepakdaneva** [cars10/elasticvue#125]
**Description**
Wherever refresh functionality is provided throughout Elasticvue we should not remove/reset the component (already fetched data) until the latest data is fetched from Elasticsearch.

**Benefits**
This breaks the user experience as the user even lost the already fetched data on the UI with the next REST API call to Elasticsearch (when clicked on refresh) also it doesn't let the user identify the changes in the old and new fetched data on the UI from Elasticsearch.

**Examples**
As an example below on the search page when the user clicks on refresh
![image](https://user-images.githubusercontent.com/68489729/201611622-92148a8e-be6e-45b6-b147-b9a81faf4dab.png)

the whole content (fetched document) is removed before even the latest data/document is fetched (as shown below) which leads to a bad user experience.
![image](https://user-images.githubusercontent.com/68489729/201612072-c537ad19-322e-4e7b-a568-a345b8a883e6.png)

**What can be done**
We can only show the progress bar but we should not remove the already-fetched document from the UI instead we should only update it as soon as we get the latest document back from Elasticsearch.

**Comment by cars10** [comment]
Fixed in `0.44.0`
