### ISSUE TITLE
[FEAT] Add a template table

### ISSUE THREAD

**Issue by bewareilive** [cars10/elasticvue#126]
Add a template table like index table to view all templates.

**Comment by bewareilive** [comment]
> Hey, what exactly do you want to achieve? Do you want elasticvue to mirror some functionality from kibana for example? Do you simply want to have a list of templates (you can always view the on the REST page ofc), or what kind of workflow are you trying to solve?



When I try to create an index, I do not remember if a template exists.Or view the template configuration.

**Comment by cars10** [comment]
![image](https://user-images.githubusercontent.com/4118628/204157424-b0d42362-8c3c-4b03-a3f9-c4a03cdcb971.png)
![image](https://user-images.githubusercontent.com/4118628/204157431-06ddbcc0-7453-4cc1-a12a-a8639a58331d.png)

I have added a very basic table to show the clusters index templates :)

**Comment by cars10** [comment]
Fixed in `0.44.0`

**Comment by bewareilive** [comment]
> ![image](https://user-images.githubusercontent.com/4118628/204157424-b0d42362-8c3c-4b03-a3f9-c4a03cdcb971.png) ![image](https://user-images.githubusercontent.com/4118628/204157431-06ddbcc0-7453-4cc1-a12a-a8639a58331d.png)
> 
> I have added a very basic table to show the clusters index templates :)

😘

But we are using version 6 and version 7 at the same time. So the template is created using "_template", not "_ index_ template".
So I cann't get my  custom templates.😆

**Comment by cars10** [comment]
Elasticvue always aims to support the two latest versions of elasticsearch, currently 7 & 8 (see [FAQ](https://github.com/cars10/elasticvue/wiki/FAQ) ). I will check the old API but i cannot promise an implementation.
