### ISSUE TITLE
[BUG] - Scrollbar is not rendered properly

### ISSUE THREAD

**Issue by deepakdaneva** [cars10/elasticvue#128]
**Description**
For the "REST" page whenever data is fetched and the scrollbar is moved to the bottom then after subsequent rest queries scrollbar does not get reset and does not move back to the top which gives the assumption that no content is changed in the left pane of elasticsearch response.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Go to the "REST" page
3. Execute any query that results in the output content of more than the visible right pane (so that we can move the scrollbar to the bottom).
![image](https://user-images.githubusercontent.com/68489729/204329740-c0c18a05-dcad-4a65-8533-94f6a4dbce3c.png)
4. Now again execute any query which results in a different output response (but make sure again content of the response is more than the div height so that scrollbar can be enabled again).
5. Now you'll see that scrollbar is not reset back to the top and is not correctly rendered even though the result visible in the right pane is from the top.
![image](https://user-images.githubusercontent.com/68489729/204331079-b1d0b82b-f180-48ad-ad95-18a2700329dd.png)

**Environment:**
* Elasticsearch version: 7.16.3
* Operating system: Windows 11 Pro
* Browser + version: Brave v1.45.133
* Elasticvue version: 0.44.0
* How are you running elasticvue? (docker, browser extension, web app): Browser Extension

**Comment by cars10** [comment]
I cannot replicate this on linux in chrome. Might be a windows / brave issue, i will check.

**Comment by cars10** [comment]
I cannot replicate this issue. I am currently rewriting elasticvue in quasar, lets hope that this fixes the issue.
