### ISSUE TITLE
[BUG] - Fix Docker Image Security Vulnerabilites

### ISSUE THREAD

**Issue by chrisbmoore** [cars10/elasticvue#129]
**Description**
Hi! I noticed that the latest image appears to contain 3 Critical and 21 High security vulnerabilities after a Docker SNYK scan. It's highly recommended to upgrade the Dockerfile to use the [latest version of nginx-alpine](https://hub.docker.com/_/nginx/tags) to prevent potential security issues if an instance is exposed to the internet. This also is important for use in corporate networks where images must be security scanned.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Do a SNYK (or similar) scan on `cars10/elasticvue:0.44.0`.
2. See reported scan vulnerabilities.

**Screenshots**
[See Attached SNYK report](https://github.com/cars10/elasticvue/files/10142927/elasticvue.Snyk.scan.txt)

**Environment (please include the following information):**
* Elasticsearch version: N/A
* Operating system: Windows 10
* Browser + version: N/A
* Elasticvue version: 0.44.0

* How are you running elasticvue? (docker, browser extension, web app): Docker.

**Additional context**
Thanks for this awesome dev tool!

**Comment by cars10** [comment]
Thanks for taking the time to run this scan. I will update the image, i guess i should simply use `stable` anyway.

**Comment by chrisbmoore** [comment]
You're welcome! Sure, stable should be safe to use as well. Thanks for taking the time for this!

**Comment by cars10** [comment]
This will be fixed in the upcoming 1.0 beta.
