### ISSUE TITLE
[FEAT] Show aliases in indices overview

### ISSUE THREAD

**Issue by Tardog** [cars10/elasticvue#13]
**Description**
I have a cluster with pairs of indices. One in each pair serves as a backup, the other is actively used for searching and indexing. An alias points at the active index.

On the Indices view, it would be helpful to add an alias column (or other indicator) to show which index is currently mapped to an alias.

**The feature is similar to..**
[elasticsearc-head](https://github.com/mobz/elasticsearch-head) displays a clear indicator with the name of an alias below the index the alias is currently mapped to.

In the image below, `bm_se_se` is the alias, and it points at the index `bm_se_se_2`.
![image](https://user-images.githubusercontent.com/22562624/70698442-c658cf00-1cc7-11ea-93b5-626becad191a.png)

**Comment by cars10** [comment]
Thank you, this is a great suggestion. I will look into it in the next few days :)

**Comment by cars10** [comment]
I just publisher ` v0.17.0` with this feature. Please let me know if you need anything else.
