### ISSUE TITLE
[BUG] 0.44.0版本MACOSx64版本无法显示数据

### ISSUE THREAD

**Issue by ljtnono** [cars10/elasticvue#131]
如图所示：
ES集群设置了跨域相关配置，但是依然无法显示任何信息

![Snipaste_2023-02-09_15-01-38](https://user-images.githubusercontent.com/37091714/217741155-c97ece52-7d03-4fff-a99f-63a2a3300aa9.png)

**Comment by cars10** [comment]
Hey, can you please translate your issue to english? I do not speak chinese

**Comment by ljtnono** [comment]
> Hey, can you please translate your issue to english? I do not speak chinese
as the picture shows:
The ES cluster has set cross-domain related configurations, but still cannot display any information.

**Comment by cars10** [comment]
Hey, sorry for the late response. Can you try to query anything in the "REST" page and see if that works?

**Comment by cars10** [comment]
This will be fixed in the upcoming 1.0 beta.
