### ISSUE TITLE
[FEAT] Cluster-specific history/state in REST tab

### ISSUE THREAD

**Issue by rdc-112** [cars10/elasticvue#133]
**Description**
I would find it useful if the history and state for the REST tab was cluster specific. I often switch between a dev and a prod cluster, and sometimes an index will be present on one cluster but not the other. 

When I switch between these indexes in the app and go to a location that is stateful such as the index field on the search tab I see the last index I used in this tab, regardless of which cluster I was using. 

The same concept is applicable for queries. I would find it useful if my query history only contained queries for the cluster I was in when I made the query. 

If you agree that this change is worth doing I would be happy to have a go at making a PR for it, subject to clarifying a few details.

**Comment by cars10** [comment]
This is a valid request and will hopefully be included in the next version. Right now a PR would not make sense because i am rewriting most of the app though

**Comment by rdc-112** [comment]
Thanks for the quick reply. Good luck with the rewrite!
