### ISSUE TITLE
Repository 'dirk' snapshots

### ISSUE THREAD

**Issue by dokterbob** [cars10/elasticvue#134]
<img width="389" alt="image" src="https://user-images.githubusercontent.com/22742/220690376-8b2b43a0-2c1b-4c16-b5cd-215363ec8eca.png">

Nope, 'Dirk' is not the name of our repo! ;)

Spotted on version 0.4.4

URL `chrome-extension://hkedbapjpblbodpgbajblpnlpenaebaa/index.html#/cluster/0/snapshot_repositories/s3/snapshots`

**Comment by dokterbob** [comment]
PS. Great stuff you built Carsten! 🥇

**Comment by cars10** [comment]
> Nope, 'Dirk' is not the name of our repo! ;)


Oh wow, seems like i accidentally left some hardcoded test data in there. Thanks, will be fixed in the next version!


> PS. Great stuff you built Carsten! 1st_place_medal

Thank you :)

**Comment by cars10** [comment]
This will be fixed in the upcoming 1.0 beta.
