### ISSUE TITLE
[BUG] - Your path.repo setting is not setup correctly (S3 repository type)

### ISSUE THREAD

**Issue by itsx** [cars10/elasticvue#135]
**Description**

I am encountering _**"Your path.repo setting is not setup correctly"**_ warning even for **S3 repository type**, which I believe is not correct. According to Elasticsearch documentation, the `path.repo` setting is used only for **Shared file system repository type**. We run Elasticsearch cluster without this setting and S3 repository works fine.

**Steps To Reproduce**

1. Setup Elasticsearch S3 repository 
2. Open elasticvue 
3. Click on Snapshots tab
4. Get Your path.repo setting is not setup correctly.

**Environment (please include the following information):**
* Elasticsearch version: 7.17.9
* Operating system: Ubuntu 22.04.1 LTS
* Browser + version: Chromium Version 109.0.5414.119 (Official Build) snap (64-bit)
* Elasticvue version: 0.44.0
* How are you running elasticvue? (docker, browser extension, web app): browser extension

**Additional context**

Elasticsearch documentation on S3 repository:
https://www.elastic.co/guide/en/elasticsearch/reference/current/repository-s3.html#repository-s3-usage
Elasticsearch documentation on `path.repo` settings:
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/snapshots-register-repository.html#snapshots-filesystem-repository

**Comment by cars10** [comment]
Hey, thanks! You are right, while building this i was only focusing on `fs` type snapshots, and these are the only ones that you can create in elasticvue. But you can obviously still see&manage other snapshots. I will improve this in the next version :)

**Comment by cars10** [comment]
You will be able to manage and create s3 repos in the upcoming 1.0 release of elasticvue :)
![image](https://github.com/cars10/elasticvue/assets/4118628/66faaf08-16b7-43a5-af70-137f052cd05d)
