### ISSUE TITLE
[BUG] - Selecting an index does not obey "Rows per page"

### ISSUE THREAD

**Issue by ms-intramanager** [cars10/elasticvue#136]
**Description**
When you select an index from the menu "Indices" the "Rows per page setting" is not obeyed. You have to switch number of rows, or sort by one of the columns

**Steps To Reproduce**
1. Open elasticvue
2. Click on "Indices"
3. Choose an index with a larger amount of rows than selected in "Rows per page"
4. See that only 10 rows are shown

**Environment (please include the following information):**
* Elasticsearch version: 8.5.3
* Operating system: Windows 11, Ubuntu 22.04
* Browser + version: Chrome +  110.0.5481.177
* Elasticvue version: 0.44.0
* How are you running elasticvue? browser extension

**Comment by cars10** [comment]
Thanks! I can reproduce this issue in will fix it for the next version :)

**Comment by cars10** [comment]
Will be fixed in the upcoming 1.0 release of elasticvue
