### ISSUE TITLE
[BUG] - Can not find templates created by myself

### ISSUE THREAD

**Issue by XiangtingLee** [cars10/elasticvue#137]
**Description**
I creat a template named test, but I can not find it in ”Index templates“ page.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Create "test" template in Elasticsearch
2. Open elasticvue
3. Click on "INDICES"
4. Click on "index_templates"
5. Filter template by name "test"

**Screenshots**
![5912cffc70d379bce60b929862dd85c8](https://user-images.githubusercontent.com/26403302/222885685-6e1883f7-0922-4227-9e63-ea6ca60d3a26.png)
![205b556d5660dc0c299b395540f157b0](https://user-images.githubusercontent.com/26403302/222885691-d1a87cf7-9a3d-46d8-8680-4c117459818c.png)

**Environment (please include the following information):**
* Elasticsearch version: 7.15.2
* Operating system: Windows 10
* Browser + version: Chrome 108.0.5359.125
* Elasticvue version: 0.44.0
* How are you running elasticvue: browser extension

**Comment by cars10** [comment]
Can you see any templates at all (so without filtering anything)?

**Comment by XiangtingLee** [comment]
I can see system template only too if witout any filter

![image](https://user-images.githubusercontent.com/26403302/224208855-e314da16-acc8-41b2-8204-f114b714efcc.png)

**Comment by XiangtingLee** [comment]
Should `/_template` API be used instead of `/_index_template`?

![image](https://user-images.githubusercontent.com/26403302/224212723-9a009775-2484-40d2-b023-72ffc69eb824.png)

**Comment by bewareilive** [comment]
This was answered in issues [https://github.com/cars10/elasticvue/issues/126]

**Comment by cars10** [comment]
This will be fixed in the upcoming 1.0 beta.

**Comment by XiangtingLee** [comment]
In v0.4.4 version, 'index templates' entrance is be placed in 'INDICES' module.
![image](https://github.com/cars10/elasticvue/assets/26403302/b9796b34-f70e-4d61-b132-a6b67cfee183)

But I can't find the index templates manage entrance in 1.0.0-beta-2 release.
![image](https://github.com/cars10/elasticvue/assets/26403302/f2e8d769-6dd5-4830-a735-6ba363a56b10)

**Comment by XiangtingLee** [comment]
I got it. Thanks for your reminding!

**Comment by XiangtingLee** [comment]
Actually, I find a way to show all templates in elasticsearch 6.x version😉
![image](https://github.com/cars10/elasticvue/assets/26403302/63e4734f-4605-4ab7-b38e-5ffd8f224ab9)
