### ISSUE TITLE
Json cannot be parsed

### ISSUE THREAD

**Issue by bewareilive** [cars10/elasticvue#138]
{
    "bbb": "333",
    //aaa
    "ccc": "444"
}
Like this,it's json5?
can be insert or query.
but search tab will report an error

**Comment by cars10** [comment]
Duplicate of #117

**Comment by bewareilive** [comment]
> Duplicate of #117

That is the query, and this is the result. Could be the same problem
![image](https://user-images.githubusercontent.com/26020170/226259604-6174e74e-64f5-4971-82a0-deff0828f6af.png)
