### ISSUE TITLE
Getting network error while making any REST calls.

### ISSUE THREAD

**Issue by anubhav6864** [cars10/elasticvue#141]
Trying to make REST calls, but getting Network Error.
Although getting the response as 200 and things are happening in the backend, but not able to display on the response window.
![Screenshot from 2023-04-25 22-05-30](https://user-images.githubusercontent.com/54501982/234344188-42998b58-ac81-4014-899a-de747d917f7b.png)
@cars10 Please take a look.
Thanks

**Comment by anubhav6864** [comment]
Now it's working, but occasionally I encounter "network error".
Also I think there is something wrong with cache management, cuz whenever I stop elasticvue,I am always able to load the page on my browser.

**Comment by cars10** [comment]
Fixed until this happens again and we have more information on the environment.
