### ISSUE TITLE
[FEAT] DELETE should be similar to GET method functionality.

### ISSUE THREAD

**Issue by deepakdaneva** [cars10/elasticvue#143]
**Description**
As of Elasticsearch v7.16.3, I believe Elasticsearch does not accept any body as part of the request. The suggestion is to remove the request body similar to when the GET method is selected so that the user doesn't have to remove it manually because it is time-consuming and frustrating.

**Specifications**
Elasticvue: `0.44.0`
Elasticsearch: `7.16.3`

**Comment by cars10** [comment]
Hey, thanks for using elasticvue :) 

Sadly there are endpoints in elasticsearch that do need a request body for `DELETE` requests, e.g. the clear scroll API. https://www.elastic.co/guide/en/elasticsearch/reference/current/clear-scroll-api.html

For this reason i cannot change the behavior.
