### ISSUE TITLE
[FEAT] There should be checkboxes available on search page for each document in the index same as indices page.

### ISSUE THREAD

**Issue by deepakdaneva** [cars10/elasticvue#145]
**Description**
When we navigate to the search page the user might want to delete the selected document from the index or all documents from the index, there should be checkboxes available against each document of the index in the grid. Once the user selects the document(s) user should be able to perform an action against them like deleting them.

![image](https://github.com/cars10/elasticvue/assets/68489729/2aeab556-1857-414b-8f75-8f80c961d02e)

**Comment by cars10** [comment]
This will be implemented in the upcoming 1.0 beta.
