### ISSUE TITLE
Utilities / Delete section is empty

### ISSUE THREAD

**Issue by fliebe92** [cars10/elasticvue#146]
**Description**
The delete section in `Utilities` page is completely empty.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on `Utilities`. 
3. See that the `Delete` section is empty.

**Screenshots**
![image](https://github.com/cars10/elasticvue/assets/8327427/90d6e96c-cd32-4d38-904d-fc7d84a13f1e)

**Environment (please include the following information):**
* Elasticsearch version: 8.1.3
* Operating system: any 
* Browser + version: any
* Elasticvue version: latest as of 2023-06-12
* How are you running elasticvue? (docker, browser extension, web app): browser extension / web app

**Comment by cars10** [comment]
This is expected for the current version. In 1.0 beta utilities will be removed an added to the rest examples.
