### ISSUE TITLE
[BUG] - [Beta] Search Tab shows wrong details when clicking on a result when doing multiple searches

### ISSUE THREAD

**Issue by maurin-at-homiwoo** [cars10/elasticvue#150]
**Description**
In the search tab, when we do multiple searches consecutively (by just changing the query dsl) the content displayed after clicking on a result is wrong (and seems to corresponds to the content of the first search).

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. The search tab and select one index
3. Type a first query 
4. Click on the 5 th result (or any other, but just remember the id and a bit of content of one result)
5. Change a bit the query
6. The new results will be displayed in the tab
7. Click on the 5th, the title of the popup should be ok but not the content

**Screenshots**
First search
![image](https://github.com/cars10/elasticvue/assets/96076076/d74c3239-9502-4845-bae1-af901c0aaff9)
I then click on the first result 
![image](https://github.com/cars10/elasticvue/assets/96076076/f7209444-3ee0-4120-a536-05e40c328e69)

Then I do a new search by changing the range (going from {40 TO \*} to {\* TO 40}
![image](https://github.com/cars10/elasticvue/assets/96076076/000d5409-3304-4f7b-8648-7c531f116415)
And if I click on the first result : 
![image](https://github.com/cars10/elasticvue/assets/96076076/c9954ae5-f2d3-4c13-8a33-8559aa61bfb6)

It also seems to happen if we change the index we search in. But if we switch to another cluster and get back again it's working correctly. 

**Environment (please include the following information):**
* Elasticsearch version: 8
* Operating system: Ubuntu 22.04
* Browser + version: Desktop App
* Elasticvue version: 1.0.0-beta1
* How are you running elasticvue? Desktop App

**Comment by maurin-at-homiwoo** [comment]
After a quick test, the issue is not present in the 0.44 in browser extension. 
Also the content of the details changed, now only the _source field is displayed, when everything was displayed in the 0.44 (including the _id field)

In 0.44 : 
![image](https://github.com/cars10/elasticvue/assets/96076076/1d14c5a8-37e2-42dc-8689-b8b5d4c79910)

In 1.0.0-beta1
![image](https://github.com/cars10/elasticvue/assets/96076076/d6c8be73-47f1-4175-8783-8d5c4a20aaac)

**Comment by cars10** [comment]
Thanks, i can reproduce the issue mentioned in your first post :)

The second point is intentional - because you can now also edit your document in this window.

**Comment by cars10** [comment]
Fixed in [beta2](https://github.com/cars10/elasticvue/releases/tag/v1.0.0-beta-2)
