### ISSUE TITLE
[FEAT] Save response body in REST tab

### ISSUE THREAD

**Issue by aka-Ani** [cars10/elasticvue#151]
**Description**
Is it possible to save the response body state in the REST tab in addition to the currently saved request body so when you switch from one tab to another and back, it is preserved?

I don't think its necessary to save it in the history list, just in the open tabs it can be pretty useful to switch back and forth tabs to compare responses without having to re-run the query.

**Additional context**
Using desktop app v1.0.0-beta-1

**Comment by cars10** [comment]
Fixed in [beta2](https://github.com/cars10/elasticvue/releases/tag/v1.0.0-beta-2)
