### ISSUE TITLE
[FEAT]Add New capability to update ssl certificate on elasticsearch cluster nodes

### ISSUE THREAD

**Issue by oncloudtraining** [cars10/elasticvue#152]
**Description**
New feature to update ssl certificates on elasticsearch cluster nodes

**Comment by cars10** [comment]
Hey @oncloudtraining , thanks for using elasticvue :) I am not sure what you mean, can you please explain this in more detail? Do you need a way to setup new certificates in your cluster? As far as i am aware there is no API for this.
