### ISSUE TITLE
[BUG] - Snapshots not listed for ES 1.5

### ISSUE THREAD

**Issue by gw-bcharboneau** [cars10/elasticvue#154]
**Description**
Apparently ES 1.5 does not have an _cat/snapshots endpoint. even though I know ES 1.5 is very old. I was wondering if it would be possible to have the snapshots section use GET /_snapshot/{repository_name}/_all instead if cluster is on 1.5? 

/_cat/snapshot endpoint was not added until sometime in ES 2.X lifecycle.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Select EleasticSearch Cluster running 1.5.X
3. Click on Snapshots
4. Click on Manage Snapshots next to desired Repository
5. will result in 404 because _cat/snapshot is not available

**Screenshots**
![image](https://github.com/cars10/elasticvue/assets/58750574/066ad0b6-76d1-47a0-bcbd-46b133118ae5)

**Environment (please include the following information):**
* Elasticsearch version: 1.5.2
* Operating system: Amazon OpenSearch Service
* Browser + version: Brave [Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)](https://brave.com/latest/)
* Elasticvue version: 0.44.0
* How are you running elasticvue? (docker, browser extension, web app): Browser Extension

**Comment by gw-bcharboneau** [comment]
The _snapshot/{repo_name}/_all endpoint is available in all versions. I am not able to upgrade the cluster at this time as there is no direct supported method of upgrade. on top of that it would mean telling our devs to re-write over 200 services that use the cluster.

I went through and tested 1.5.2, 2.3, 5.3.2, 5.5.2 and 7.10 for the existence of the _snapshot endpoint as well as the _snapshot/{repo_name/_all endpoint and they exist in all versions, not just 5, 6 and 7.

I tested this because we have other clusters on newer versions, but the schema for 1.5.2 cannot be moved to newer versions. I have tried.

**Comment by gw-bcharboneau** [comment]
Thanks, that is all I ask is that you look into it.
I will admit this though. the JSON Body is a little different between the 2 endpoints. so a little work on parsing may be required.
But the format remains consistent in all versions I checked.

the capture/restore snapshot endpoints is 100% the same as in newer versions. it's tjust the list or get snapshots endpoint the would be needing a change here

**Comment by cars10** [comment]
This will be fixed in the upcoming beta 3 release :)

**Comment by cars10** [comment]
I have released `beta-4` with this fix included. Thanks for the tip, the endpoint actually makes things much simpler. You should be able to use snapshots with every version of elasticsearch.
