### ISSUE TITLE
[BUG] -Long type id can not show correctly in windows client

### ISSUE THREAD

**Issue by liangxiong3403** [cars10/elasticvue#155]
The same data, show correctly  in Chrome extension, but not in windows client.

right show:
![image](https://github.com/cars10/elasticvue/assets/27960242/700eadc0-81c2-410f-a2fb-305fdef66f7e)

error show:

![image](https://github.com/cars10/elasticvue/assets/27960242/eae2a38a-9be9-45dd-9a09-659c24ece137)

**Comment by cars10** [comment]
Will be fixed in `beta-5`. Even though using numbers this big will cause issues of all kinds in almost any environment, you should consider using strings for that.

**Comment by cars10** [comment]
Fixed in [beta5](https://github.com/cars10/elasticvue/releases/tag/v1.0.0-beta-5)

**Comment by liangxiong3403** [comment]
thanks
