### ISSUE TITLE
[BUG] - Ram usage shown is not consistent

### ISSUE THREAD

**Issue by vdere** [cars10/elasticvue#157]
**Description**
Ram usage shown for the node in elasticvue is inconsistent with what is shown in the instance.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on Nodes
3. Check Ram column

**Screenshots**
![image](https://github.com/cars10/elasticvue/assets/29939847/052ab1de-b607-4980-84ab-fd31617bea64)
![image](https://github.com/cars10/elasticvue/assets/29939847/bc735113-d3a8-4ba6-87f3-f7bf47448cc3)
![image](https://github.com/cars10/elasticvue/assets/29939847/b0af52e0-7043-4ba9-8609-4f778225066a)

**Environment (please include the following information):**
* Elasticsearch version: 7.7.0
* Operating system: Cent OS
* Browser + version: Edge 116.0.1938.62
* Elasticvue version: 0.44.0
* How are you running elasticvue? (docker, browser extension, web app): browser extension

**Comment by cars10** [comment]
The nodes view uses the information provided by the `_cat/nodes` endpoint. Please check a `GET _cat/nodes?h=ram.current,ram.max,ram.percent` to validate

**Comment by bebehei** [comment]
I just started using ElasticVue instead of Cerebro.

Having a RAM overview is useful on the one hand side, but since I'm [running on Linux a 100% is actually perfect](https://www.linuxatemyram.com/).

From UX perspective the overall RAM usage is totally useless then.

Shouldn't the column be renamed to Heap usage and `heap.percent` used instead as the reported value?

**Comment by cars10** [comment]
Hey @bebehei , which version of elasticvue are you using? Elasticvue shows heap and ram for many years.

![Image](https://github.com/user-attachments/assets/2e294a51-5852-4c86-aa91-aef0eb74c1e9)

**Comment by bebehei** [comment]
I'm using latest. And I had been blind.

Sorry for the noise.
