### ISSUE TITLE
[BUG] - UI Freeze when reindexing a big index

### ISSUE THREAD

**Issue by MoeNadal** [cars10/elasticvue#158]
**Description**
The interface is not responding anymore when reindexing a big index. 
Even after the reindexation is done (I'm checking with some rest queries made outside of elasticsearch)

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Find a big index (several Gigs)
3. Reindex it using the reindex method
4. Elasticvue simply freeze on the reindexing popup, the only possible action is then to close the window and open it again. 

**Environment (please include the following information):**
* Elasticsearch version: 8.6
* Operating system: Ubuntu
* Elasticvue version: Desktop Beta 1.0.2
* How are you running elasticvue? (docker, browser extension, web app): desktop version

**Comment by maurin-at-homiwoo** [comment]
(wrong github account used to create this issue, adding this comment to follow the issue and be faster to react if you need anymoore information)

**Comment by cars10** [comment]
Hm, thats weird. Can you reproduce this issue or was it a one-time thing?

**Comment by maurin-at-homiwoo** [comment]
Seems quite reproducible, I did 3 re-indexing and it freezes 3 times. 
The reindexing takes around 15 minutes (20Gig index).

**Comment by cars10** [comment]
Sorry but i still cannot replicate this issue. Could you maybe try to start a reindex "manually" by using the REST functionality?

**Comment by cars10** [comment]
I still can't reproduce this issue. Please try again with version 1.0 where i do not wait for completion of the reindex - maybe this changes things. Thanks!
