### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by vipcxj** [cars10/elasticvue#159]
**Description**
Connect to es on the server side

**The feature is similar to..**
Does the feature exist in a similar tool (for example `kibana`)? If so, please:
Yes kibana
* link the tool
* explain how/where to use the feature
* if applicable, add screenshots to help explain the feature 

**Additional context**
Anything else?
The es is in the k8s cluster, I don't want public it. So I need a web ui running in the cluster which can connect to the es, and public this web ui.

**Comment by cars10** [comment]
You can run elasticvue as a docker container in your cluster and expose that :)

**Comment by vipcxj** [comment]
@cars10 what about setup a proxy server with elasticvue which proxy only es api?

**Comment by cars10** [comment]
This would be exactly what a port forward in k8s would do :) But you can also use any other proxy server of course.

**Comment by vipcxj** [comment]
@cars10 The problem is I can't tell which connections are es's and which are elasticvue's own.

**Comment by cars10** [comment]
You need to forward your elasticsearch port (typically 9200) to your local machine. Then, in elasticvue, connect to `localhost:9200` :)

**Comment by vipcxj** [comment]
@cars10 I known the workaround, but I want a formal solution. Such as elasticvue tag all connection to es, then forward the request to es in its server in the cluster (Configuring the es host using env for the proxy server), then I can setup a auth proxy for elasticvue only, no need to public the es, and I can admin es anywhere without config the k8s proxy. Generally, not everyone has permission to use k8s proxy. I have setup like this for mongodb, redis, postresql, kibana and so on. but stuck in for es.

**Comment by floviolleau** [comment]
Hi,

I just jumped in that discussion and I have exactly the same issue. Can we have a solution ?

Thanks

**Comment by cars10** [comment]
The solution is to either use a local proxy (like https://github.com/cars10/simprox ) or to use the desktop application of elasticvue.
