### ISSUE TITLE
[FEAT] Filter duplicates in the History for the Rest Tab

### ISSUE THREAD

**Issue by maurin-at-homiwoo** [cars10/elasticvue#162]
**Description**
The history is quickly filled up with duplicates when we use the rest tab to monitor a bit the cluster (health or status request). It would be useful to only keep one entry per request to avoid that. 

**The feature is similar to..**
Only keep the last instance of a request in the history (including the body in the diff as sometime only the body differs). It might be possible to only do the filtering on the get request as they never have a body.

**Comment by cars10** [comment]
Will be fixed in beta-7.
