### ISSUE TITLE
[FEAT] Link to the docs of the active cluster version

### ISSUE THREAD

**Issue by nuno-andre** [cars10/elasticvue#163]
The _API DOCUMENTATION_ link in the _REST_ tab links to the latest (current) version of ES, i.e.

https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html

Linking to the active cluster minor version would be more helpful, e.g.

https://www.elastic.co/guide/en/elasticsearch/reference/8.7/index.html

Also, maybe you could link directly to the REST APIs documentation instead of the reference index.

https://www.elastic.co/guide/en/elasticsearch/reference/8.7/rest-apis.html

**Comment by cars10** [comment]
The `rest-apis` page is only available for ES 7 & 8, but linking to the current version docs in general is a good idea.

**Comment by cars10** [comment]
Will be fixed in `beta-6`.
