### ISSUE TITLE
[BUG] - Filter on indicies page is not working

### ISSUE THREAD

**Issue by petermoberg** [cars10/elasticvue#164]
**Description**
Filter on indicies page is not working

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Connect to cluster
2. Click on "Indicies" in the main menu
3. Enter something in the filter input 

Expected behavior:
- The Indicies displayed are filtered according to the input

Actual behavior:
- Nothing happens

**Environment (please include the following information):**
* Elasticsearch version: 7.10
* Operating system: MacOS
* Browser + version: NA
* Elasticvue version: Version 1.0.0 (20230911.170550)
* How are you running elasticvue? (docker, browser extension, web app): Desktop app

**Additional context**
Thanks for providing a great tool!

**Comment by cars10** [comment]
Thanks, this is already fixed on dev and will be included in the next version.
