### ISSUE TITLE
Add input ca certificate

### ISSUE THREAD

**Issue by HUAHUAI23** [cars10/elasticvue#167]
I deployed elasticvue and elasticsearch in the same k8s cluster, the network of elasticvue and elasticsearch is connected, is it possible to connect to my elasticsearch as long as I enter the ca certificate, but I didn't find a place where I can enter the certificate, in the same way, I use nodejs elasticsearch client to connect to my elasticsearch.

![image](https://github.com/cars10/elasticvue/assets/43649186/369d91eb-63f6-4902-85f7-5ac58af73749)

![image](https://github.com/cars10/elasticvue/assets/43649186/e80ca913-8082-46a1-b18b-c452d725e311)

![image](https://github.com/cars10/elasticvue/assets/43649186/cab7eb7a-9301-412d-8599-23d9daf5d542)

**Comment by HUAHUAI23** [comment]
> in the same way, I use nodejs elasticsearch client to connect to my elasticsearch.

ca certificate is self signed certificate

**Comment by cars10** [comment]
Because elasticvue runs completely in the browser your elasticsearch cluster need to be accessible by your client. If you use an untrusted certificate you have multiple options to connect to your cluster, please check https://github.com/cars10/elasticvue/wiki/Access-clusters-using-SSL
