### ISSUE TITLE
[FEAT] Add node attributes to display

### ISSUE THREAD

**Issue by l0calhost** [cars10/elasticvue#169]
**Description**
Elasticsearch allows to set attributes to the configuration (`node.attr.*`). It would be very helpful to see these attributes (maybe even sortable?) in the "Nodes" table and "Shards" overview for adding certain information to a cluster node, e.g. datacenter location.

**The feature is similar to..**
Cerebro displays these attributes at the "overview" and "nodes" page. 

Example: 
- To see them, add "node.attr.datacenter: rza" to your elasticsearch.yml
- Cerebro will display "rza" below the node name as a label or tag.

![image](https://github.com/cars10/elasticvue/assets/8111901/4b227432-506a-44c4-92c6-cc140ea032b9)

**Comment by cars10** [comment]
Showing attribute values without a corresponding label to show what they are even about is quite confusing in my opinion - but i will try to include node attributes. Possibly in a different way then cerebro

**Comment by l0calhost** [comment]
You're right, corresponding label would be even more helpful! 👍

**Comment by cars10** [comment]
Node attributes will be included in the next version:
![image](https://github.com/cars10/elasticvue/assets/4118628/2820889f-1970-4117-9a5e-f63a984bddc7)

You can also define a regex to hide attributes that you dont need, defaulting to all `ml.`, `transform.` and `xpack.` attributes
![image](https://github.com/cars10/elasticvue/assets/4118628/c2136ad1-3317-44ed-b908-61ace0d899ec)

**Comment by l0calhost** [comment]
Awesome, thank you very much, @cars10 ! That's what i call a very welcomed christmas gift! 🙂 Looks very good, and to possibility to filter makes it even better, haven't thought about that before. Thanks again, great work! 👍🏻
