### ISSUE TITLE
[BUG] - Existing Index templates not displaying

### ISSUE THREAD

**Issue by l0calhost** [cars10/elasticvue#170]
**Description**
Existing index templates of an elasticsearch cluster are not displayed.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on "Indices".
3. Click on "Index Templates".
4. See nothing. :)

**Screenshots**
Elasticvue:
![image](https://github.com/cars10/elasticvue/assets/8111901/73df6dec-f27a-4d27-9778-2952f5b7a380)

Same cluster in Cerebro:
![image](https://github.com/cars10/elasticvue/assets/8111901/d06292ef-8e2f-4155-a1ff-6c05903c0895)

**Environment (please include the following information):**
* Elasticsearch version: 7.10.2
* Operating system: RHEL 8.9
* Browser + version: Chrome 119.0.6045.124
* Elasticvue version: Elasticvue 0.44.0 (Browser Extension)
* How are you running elasticvue? browser extension

**Additional context**
Developer Console says, Elasticvue calls `https://<URI>/_index_template/` to get index template information. 
When trying manually with curl, this returns `{"index_templates":[]}`. 

According to the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/indices-get-template-v1.html) the url should be 

`https://<URI>/template/` 
or `https://<URI>/template/*`. 

These return the expected index template data when curled.

**Comment by cars10** [comment]
The API you are referring to is the legacy API. It seems like your templates are not migrated yet, see the info box at  the top here: <https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-template-v1.html>

**Comment by l0calhost** [comment]
*Closed*
