### ISSUE TITLE
[FEAT] The cluster's host shown in the browser's address, likes: "chrome-extension://hkedbapjpblbodpgbajblpnlpenaebaa/index.html#/cluster/http%3A%2F%2Fwww.elasticsearch.com%2Fcluster/"

### ISSUE THREAD

**Issue by guangfanqu** [cars10/elasticvue#173]
**Description**
* We have many clusters, and we want to maintain the clusters Elasticvue, 
* All the clusters have the same ApiKey. If configure the ApiKey in the system "settings"
![image](https://github.com/cars10/elasticvue/assets/46156181/6482aabc-4b0d-40f2-94e7-074a2b42dff4)
* So we can jump to Elasticvue with the cluster's host without ApiKey (setting in global configuration) , it's useful to us.

Thx.

**Comment by cars10** [comment]
Hey @guangfanqu , thanks for using elasticvue :) Unfortunately i dont think that using the same password for many clusters is a common usecase. I will close this issue for now, might revisit in the future if more people need this.
