### ISSUE TITLE
The last filtered indices will be retained by default, and it cannot be used after updating

### ISSUE THREAD

**Issue by JackSeven** [cars10/elasticvue#181]
**Description**
When opening the indices page, the last filtered indices will be retained by default, and it cannot be used after updating

**Steps To Reproduce**
1，opening the indices page
2，filtered indices
3，close indices page，and reopen it
4，filtered keyword cannot be used

**Screenshots**

**Environment (please include the following information):**
* Elasticsearch version: 6.8.6
* Operating system: MacBook Pro (Retina, 15-inch, Mid 2015)
* Browser + version: Chrome 120.0.6099.129 (x86_64)
* Elasticvue version: 1.0.0 => 1.0.1

**Additional context**
I didn't do any configuration extension actions, I just updated the system, and after opening Google Chrome, it was like this. May I ask if it is possible to keep this feature? After opening the extension, the last filtered index keyword will be retained by default?

**Comment by cars10** [comment]
Fixed in `1.0.2`.

**Comment by JackSeven** [comment]
Thank you so much
