### ISSUE TITLE
[FEAT] Rest Submit ShortCut

### ISSUE THREAD

**Issue by hdhakernk** [cars10/elasticvue#183]
**Description**
Please describe the feature here.

In Rest Section A shortcut to submit the query. 
E.g. CTRL+Enter Can be consider to submit the query 

**The feature is similar to..**
Does the feature exist in a similar tool (for example `kibana`)? If so, please:
* link the tool
* explain how/where to use the feature
* if applicable, add screenshots to help explain the feature 

**Additional context**
Anything else?

**Comment by cars10** [comment]
Alt+Enter should do it. What OS are you using?

**Comment by hdhakernk** [comment]
Hi,

I'm using Ubuntu 20.
I used to do CTRL+Enter for submit. I was not aware of ALT+Enter is working
here.
I tried the same. it's Working fine.

Every website like What's app web, Google Chat, Slack has shortcut like
CTRL+Enter.
Can we add CTRL+Enter as well for the same operation?


Thanks & Regards
NARENDRA DHAKER
810-980-7855

**Comment by cars10** [comment]
Fixed in `1.0.2`.
