### ISSUE TITLE
Support login using Authorization Header

### ISSUE THREAD

**Issue by archongum** [cars10/elasticvue#184]
**Description**
Support login using Authorization Header

**Example**
curl --request GET \
  --url http://localhost:9200/ \
  --header 'Authorization: Basic Y2hlYmFiYxxxxxxxxxxxxxxxxx'

**Comment by cars10** [comment]
Elasticvue alerady sets the Authorization header when you provide credentials (username+password or api key). I am not sure what you expect?

**Comment by archongum** [comment]
> Elasticvue alerady sets the Authorization header when you provide credentials (username+password or api key). I am not sure what you expect?

I am confused too but someone just give me this Header instead of username+password.

**Comment by archongum** [comment]
@cars10 It turns out I can de-base64 this Authorization value to get username+password... Sorry about this mess, closed.

**Comment by cars10** [comment]
Great, this is exactly what i just wanted to propose :)
