### ISSUE TITLE
[FEAT] Implement Connection to Clusters over SSH

### ISSUE THREAD

**Issue by marisac3141** [cars10/elasticvue#186]
**Description**
As it says on the tin, it would be very handy to connect to a remote cluster over SSH. I manage a number of websites but don't seem to have a way to connect to clusters over SSH (if there is a way, I'm happy to learn). The clusters are not world accessible... as in you can't access the ES/OS API when not shelled into the server. Ideally, I'd like to see support for jump hosts as well.

**The feature is similar to..**
I use RedisInsight-v2 for Redis clusters and it works very well for what I need.
Link: https://redis.com/redis-enterprise/redis-insight/
When you fire it up, you can add a new connection (much like EV) but you can use an SSH tunnel to connect to the cluster.

**Additional context**
I like what this can provide but SSH would be very beneficial. I use the desktop version on Windows 11 Pro.

**Comment by cars10** [comment]
Sadly this ist not possible. Elasticvue runs completely in the browser, and you cannot create a ssh connection in javascript.

But you can simply create an ssh tunnel in your terminal and connect to your forwarded local port. This ist exactly what native tools like the mentioned redis client so.

**Comment by marisac3141** [comment]
Thanks for the info. I figured out how to configure everything.
