### ISSUE TITLE
[BUG] - New version is missing document metadata info such as "_version", etc

### ISSUE THREAD

**Issue by cadeveloper00** [cars10/elasticvue#187]
**READ BEFORE OPENING AN ISSUE**
Before you submit an issue please try to reset elasticvue and see if you can reproduce the problem.
To reset please click `Disconnect and reset` in the footer, this will reset all your saved filters and you have to reconnect to your cluster.
Proceed and open an issue if your problem persists.

**Description**
When browsing the document, it used to be that we are able to view all the internal metadata such as "_id", "_score", "_version", etc. Those are no longer there. Can you please bring those back? 

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on an index
3. Click on a document
4. Document no longer show the metadata structure such as "_id", "_version", etc.

**Comment by cars10** [comment]
Fixed in `1.0.2`.
