### ISSUE TITLE
Is it possible to revert the editor back to the old 0.x version

### ISSUE THREAD

**Issue by Bronya0** [cars10/elasticvue#189]
Is it possible to revert the editor back to the old 0.x version? 
I find it very frustrating that, upon entering curly braces, the prompt immediately appears, preventing me from pressing Enter to create a new line
![image](https://github.com/cars10/elasticvue/assets/55728567/c7be9545-0bf0-410f-8a4f-d21eec1530e7)

![image](https://github.com/cars10/elasticvue/assets/55728567/7af3e2f5-7165-4f2e-9097-4230575fe60a)

**Comment by cars10** [comment]
This is indeed quite annoying. Will be fixed in the next version :)
