### ISSUE TITLE
Save settings and accepting Enter

### ISSUE THREAD

**Issue by bdliliedahl** [cars10/elasticvue#190]
**Description**
This is something that used to work but no longer does. You used to be able to hit Cmd+Enter (Ctrl-Enter on non-Mac) from the Query window to run the query, which made it very easy to search. Now you are forced to click the Search button. Huge time waster.

Secondly, if you change the records per page setting, it does not remember this, and always reverts back to 10.  Very annoying behavior.

**Comment by bdliliedahl** [comment]
FYI - the Alt key on Mac is mapped to the Option key. But Option+Enter does not work either. Looking forward to the Ctrl+Enter fix, thank you!

**Comment by cars10** [comment]
On Mac it should be cmd+enter.
