### ISSUE TITLE
[FEAT] Globally accessible saved REST queries

### ISSUE THREAD

**Issue by kclejeune** [cars10/elasticvue#194]
**Description**
The ability to save REST queries is super useful for keeping track of commonly used API requests and other snippets. There are several common/generic ones that I'd like to bring along to every ES cluster I need to interact with, but currently this feature appears to be scoped to a particular cluster.

As a user, I'd like to be able to mark a "saved query" as globally accessible to the entire ElasticVue extension (available for use in any cluster registered with the extension). Maybe this is a checkbox on the saved queries for a particular cluster, or maybe it's a whole separate menu? I'm not much of a UX person so unfortunately I'm probably not qualified to provide much input on how it should look :(

**The feature is similar to..**
This feature is _vaguely_ inspired by my postman request history, which I used to rely on extensively prior to using this extension! It's maybe like a hybrid of an API collection combined with the "environments" feature, if you think of each individual ES cluster as an environment...not sure that's the best comparison, but hopefully you get my drift.

Hopefully this description makes sense - happy to discuss further if not!

**Comment by cars10** [comment]
This feature is currently not planned. Might revisit if the upcoming survey indicates a general need.
