### ISSUE TITLE
possibility to change the font size

### ISSUE THREAD

**Issue by fernandomacho** [cars10/elasticvue#195]
**Description**
Is possible that you add on config the option to change the font size?

For example on 1920x1080 monitor all interface is too big

And some "windows", for example edit data has two scrolls: the data scroll and the update "window"

Thanks in advance

**Comment by cars10** [comment]
regarding #2) If you increased the size of the modal then you will obviously have two scrollbars. Decrease the size of the editor in the modal if that is an issue for you.

**Comment by cars10** [comment]
Hey, does zooming out not work for you?

**Comment by fernandomacho** [comment]
No, the zoom not workEl 31 ene 2024, a las 17:31, Carsten König ***@***.***> escribió:﻿
Hey, does zooming out not work for you?

**Comment by cars10** [comment]
Currently blocked by https://github.com/tauri-apps/tauri/issues/3310 . Will implement once this is fixed in tauri
