### ISSUE TITLE
[BUG] - Updating removes saved queries

### ISSUE THREAD

**Issue by valpet93** [cars10/elasticvue#196]
I used to save frequent queries in REST section, by "starring" them.

When the new update was pushed through the app store, all the saved queries are reset although clusters are not.

1. Open elasticvue < 1.0
2. Click on REST
3. make query and save it as preferred
4. update elasticvue >= 1.0
5. click on REST
6. open saved query

 Elasticsearch version: 1+
 Operating system: Windows
 Browser + version: Chrome 120
 Elasticvue version: 1.0.3
 How are you running elasticvue? (docker, browser extension, web app): browser extension

**Comment by cars10** [comment]
Hey, elasticsearch 1.x is not officially supported by elasticvue. Copy/paste from the wiki:

>Elasticvue always has full support for the two latest major versions of elasticsearch. Currently this means 8.x, 7.x. Older versions of elasticsearch should work, but you might encounter small bugs or limited features.

While elasticsearch 1.x mostly works, there was no migration path for it for elasticvue. The data is probably still there if you need to manually extract certain queries. You can do that by checking the indexeddb content in your browser.

**Comment by valpet93** [comment]
Sorry my bad. I was meaning elasticsearch 7+
