### ISSUE TITLE
[FEAT] Dev tools in Elasticvue

### ISSUE THREAD

**Issue by DagW** [cars10/elasticvue#197]
**Description**
Elasticvue is really good, thanks for creating it. 
The one thing Im missing is the dev tool workspace, like in kibanan or opensearch dashboards.

Is it possible to integrate that instead of the REST-tab?

example:
![bild](https://github.com/cars10/elasticvue/assets/289691/6e78400a-069b-4dcc-92b2-2936643a7061)

**Comment by cars10** [comment]
Closed until we have more information on missing features.

**Comment by olucafont6** [comment]
@cars10 I think the Dev Tools layout has two main benefits.

The first one is that it's sometimes a nicer experience to be able to have multiple queries on the same page that you can copy, modify, and then execute independently of each other. With the REST tab, you have to click on a different tab every time you want to get to your older queries.

Admittedly having all of your queries on one big scroll-able vertical page is not great for organization, but I think it's nicer in some cases.

The second benefit (which isn't necessarily tied to the Dev Tools layout), is that we get type-ahead / suggestions for the available endpoints and index names - e.g.:

<img width="328" height="156" alt="Image" src="https://github.com/user-attachments/assets/1c10e0e9-1747-4b95-83c3-7d700ab57ebd" />

This can be very helpful when you're not exactly sure what an index is named. 

The Search tab does kind of have something like this in the Select indices mode, but it seems like the REST tab will only suggest indices you've previously selected. 

I think independent from the type-ahead / suggestions filter though, the Dev Tools layout would still be nice to have.
