### ISSUE TITLE
[FEAT] Use elasticsearch sort functionality

### ISSUE THREAD

**Issue by KLIM8D** [cars10/elasticvue#20]
**Description**
It would be nice if the solution could use the "Multi Search API (_msearch)" instead of just _search. In the way sorting and more could be done by elastic.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html#search-multi-search

As it is now, you could potentially hide records/information from the user, if you have more than the default 1000 records that's fetched.
Let's say there are 1500 records in ES. The 1000 records are fetched to the frontend, and the user sorts on a date field in descending order. Because only the first 1000 records are fetched, the #1000 record are at the top now and not #1500 as I would expect.

**The feature is similar to..**
Dejavu uses _msearch
https://github.com/appbaseio/dejavu

**Comment by cars10** [comment]
Hi, i dont think that _msearch would make sense for elasticvue. Right now the frontend only allows you to execute a single query anyway. But using the sort functionality of elasticsearch makes a lot of sense, and this is also possible with the regular _search endpoint. I will look into that :)

**Comment by cars10** [comment]
Hey @KLIM8D , elasticvue version 0.22.0 now uses server side sorting. You can already try in the hosted version and the docker image. 
The browser extensions still take some days until they are published :)

Thanks again for the proposal!

**Comment by KLIM8D** [comment]
It looks great, thanks! :)
