### ISSUE TITLE
[BUG] - "elasticvue.app" is damaged on macOS

### ISSUE THREAD

**Issue by mikucat0309** [cars10/elasticvue#204]
**Description**

> “elasticvue.app” is damaged and can’t be opened. You should move it to the Trash.

**Steps To Reproduce**

1. Download `elasticvue_1.0.3_aarch64.dmg` from GitHub release page
2. Double click open elasticvue.app

**Screenshots**

![image](https://github.com/cars10/elasticvue/assets/47076023/180cc4e5-4920-4fb2-ad8a-313735b1bf75)

**Environment (please include the following information):**
* Elasticsearch version: 7.15.2
* Operating system: MacBook Pro M2 / macOS Sonoma 14.2.1
* Browser + version: N/A
* Elasticvue version: 1.0.3
* How are you running elasticvue? (docker, browser extension, web app): web app

**Comment by cars10** [comment]
Please read the hint in the release notes:
https://github.com/cars10/elasticvue/releases/tag/v1.0.3
