### ISSUE TITLE
Predefined cluster 

### ISSUE THREAD

**Issue by Navirash** [cars10/elasticvue#208]
Hello,

I deployed Elasticvue on Kubernetes. In the deployment configuration, I pre-defined the Elasticsearch clusters using the environment variable ELASTICVUE_CLUSTERS.

When I run kubectl port-forward service/elasticvue-service http 8080, I can see the pre-defined clusters.

However, when I go through a host configured by the ingress: https://app.elastic.com/, I can't see the pre-defined clusters. I get an error: "Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data."

Do you have any idea what the problem might be, please?

**Comment by cars10** [comment]
Hey @Navirash , sorry for the late response. I guess you could solve the issue? :)

**Comment by Navirash** [comment]
Hi @cars10 , it was just a cache issue. It was caching a wrong value for ELASTICVUE_CLUSTERS. I added a "no-cache" directive at the ingress level, and that fixed the problem.
