### ISSUE TITLE
[BUG] - Add S3 Repository for AWS missing role_arn option

### ISSUE THREAD

**Issue by gw-bcharboneau** [cars10/elasticvue#209]
**Description**
The UI does not allow adding an S3 Bucket Repository on AWS Managed Clusters because it is missing an option for settings.role_arn
The Following Error is presented:

{"Message":"settings.role_arn is needed for snapshot registration."}

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on Snapshots
3. Click on New Repository
4. Fill out info, selecting S3 for repository type
5. No option to add role_arn is avaialble
6. Click Create
7. see error in bottom right corner

**Screenshots**
![image](https://github.com/cars10/elasticvue/assets/58750574/ac260fa3-3075-47da-bd7f-3bc725c21b6b)

**Environment (please include the following information):**
* Elasticsearch version: 
* Elasticvue version: 1.0.3-stable
* How are you running elasticvue? Desktop and Firefox Extension
* Screenshot from windows desktop app

**Additional Info**
here is an example json body that gets sent to an AWS Elastic/OpenSearch Cluster to create a repo that uses S3

```
{
    "type": "s3",
    "settings": {
        "bucket": "{{Bucket}}",
        "base_path": "{{SnapshotName}}",
        "role_arn": "{{RoleArn}}",
        "region": "{{Region}}"
    }
}

there are also other optional settings such as 

- "readonly": {true/false}
- "server_side_encryption": {true/false}

**Comment by cars10** [comment]
Can you provide documentation for the `role_arn` option? This does not seem to be listed anywhere in the docs.

**Comment by gw-bcharboneau** [comment]
sure See Step 2 and select Snapshots as it may default to encrypted snapshots
[Creating index snapshots in Amazon OpenSearch Service](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-snapshots.html)

![image](https://github.com/cars10/elasticvue/assets/58750574/6e9b1d7b-5a1a-4284-ac1d-11b945a1c6a3)

**Comment by cars10** [comment]
Thanks, so we are talking about **opensearch** and not elasticsearch. I will add this to #191

**Comment by gw-bcharboneau** [comment]
It’s ElasticSearch too. If it is hosted on AWS, they renamed their service to “AWS OpenSearch Service” but it encompasses both (ElasticSearch Version up to 7.10) and (OpenSearch 1.x and 2.x).  they changed their Service name, and started pushing opensearch because of Elastic changing their licensing model.

**Comment by cars10** [comment]
I know the history of opensearch. But i am not able to find the option `role_arn` anywhere in the official **elasticsearch** docs, thats why i assume its opensearch only.

**Comment by gw-bcharboneau** [comment]
it is because it is a customization that AWS made to allow users to access S3 without making the S3 bucket Public. it has been there since version 1.5 on AWS Managed clusters only.

**Comment by gw-bcharboneau** [comment]
All I am asking for is an optional parameter for IAM Role Arn for AWS Managed clusters. is this something you would be willing to look into?

**Comment by cars10** [comment]
I will look into this. In the meantime, you can always use the `rest` page to manually run queries as you do in postman.
