### ISSUE TITLE
[FEAT] Where to find logs for the desktop app?

### ISSUE THREAD

**Issue by bfontaine** [cars10/elasticvue#211]
**Description**
Hello, I still have this [annoying issue](https://github.com/cars10/elasticvue/issues/105#issuecomment-1746648690) on the desktop app v1.0.3, but it occurs only on some indices of one cluster so it’s hard to help you reproduce it.
Is there some place I can find logs to troubleshoot the issue?

**Comment by cars10** [comment]
Elasticvue desktop does not really offer much in terms of logging right now. I attached a version of the current develop branch that has the debug console enabled - you can use the browser console to check for any frontend errors.
[elasticvue.zip](https://github.com/cars10/elasticvue/files/14409500/elasticvue.zip)

* right click anywhere
* inspect element
* console

Thanks for helping me debug this issue!

**Comment by bfontaine** [comment]
Thanks! I downloaded 1.0.4 and opened the console, but I don’t see anything. I also don’t see requests in the network tab when I click on "refresh" on any of the views that have it.

This is what I have in the network tab after having navigated multiple times on all views (Home/nodes/shards/etc) and clicked on "refresh" on indices and shards multiple times:
![image](https://github.com/cars10/elasticvue/assets/1334295/3bb75da5-a31c-4331-99b5-89530af69e5d)

The only requests I see are those made when I switch cluster, but those are HTML/JS/CSS/font/images, not actual requests to ES.

When it freezes, I can move around in the inspecter tab, but I can’t expand the HTML elements anymore:
![image](https://github.com/cars10/elasticvue/assets/1334295/82d34372-fd67-47f9-ab3e-94ea5af9c699)
Here you can see some little arrows that point down in the HTML view but the content of these elements is not shown, because the inspecter is as frozen as the view. In fact, I did <kbd>alt</kbd>+<kbd>tab</kbd> to write this here and then go back to ElasticVue, and it turned all white:
![image](https://github.com/cars10/elasticvue/assets/1334295/a3c520c1-8413-45d8-8d75-85b1db8b415d)
(I resized it because we don’t need a large screenshot to see that it’s empty)

**Comment by cars10** [comment]
Hm, i will add more logging for the desktop app. 

Can you reproduce the freezing issue when reindexing via the REST page? Or does it only happen on the indices page when using the reindex functionality?

**Comment by bfontaine** [comment]
Wait I found the issue: I went to a small index (2.5k documents) on the "Search" page, it froze _but_ only for ~10s or so, then it showed the list of documents and was almost unresponsive but still "usable". The list of documents was very long because the limit was set to 10k records per page; when I set it back to 20, the page became responsive again. I went to a larger index (100M+ documents) and it didn’t freeze.

The issue seems to be that at one point I set the limit to 10k records per page, probably on a small index, and then this configuration was saved for the whole cluster, so on large indices it probably froze while trying to retrieve all these documents.

**Comment by Garito** [comment]
The frozen app shows up with small amount of huge documents too
To reproduce it save the response of gcloud's documentai of a page with a lot of text and try

**Comment by cars10** [comment]
Hello @Garito , can you reproduce this with the latest version (1.1.0)?

**Comment by Garito** [comment]
Yes, I can confirm
It is a matter of a huge doc loaded to memory even in the list view (imagine 10, 100, etc)
If I disable the huge field in the view it goes back to "normal"

**Comment by Garito** [comment]
A suggestion then:
the copy button should copy the complete doc

**Comment by Garito** [comment]
Thanks btw

**Comment by cars10** [comment]
> A suggestion then: the copy button should copy the complete doc

You can copy a document when you opened it (double click table row, then click copy Icon in editor in modal)

**Comment by Garito** [comment]
I know
I meant that if you truncate the modal too (and you should, imo), the copy button should work as expected and copy the whole doc
BTW, talking about the modal and this huge docs, the colapse icon tends to not show up, at least, at the middle of the doc

**Comment by cars10** [comment]
> I know I meant that if you truncate the modal too (and you should, imo), the copy button should work as expected and copy the whole doc BTW, talking about the modal and this huge docs, the colapse icon tends to not show up, at least, at the middle of the doc

The modal will never be truncated. This does not make sense, because a) we need a place to show the whole doc and b) you can edit the doc there. Saving would destroy the data if i only put truncated text in there.
You can toggle the wrap lines option in the modal to help with longer lines

**Comment by Garito** [comment]
I understand but you should try what I tell you about documentai or any other huge doc:
<img width="1440" alt="Captura de pantalla 2024-11-22 a las 12 41 17" src="https://github.com/user-attachments/assets/87b6dcf8-de92-4dde-854a-6e8675605c99">
It takes a fair amount of time to load
Beside that, the toggler doesn't  always show up there as you can see
