### ISSUE TITLE
[BUG] Unable to retrieve records after upgrading to ES 8.12.2

### ISSUE THREAD

**Issue by terzano** [cars10/elasticvue#212]
Unable to **Search** for records on Elasticvue Desktop App v1.0.3 after upgrading cluster to latest 8.12.2. 
Indices listing, Nodes and Shards information still works.

**Comment by sachinbhapkar** [comment]
Unable to filter the results of snapshot.
![image](https://github.com/cars10/elasticvue/assets/31815217/80901155-cb9f-404b-ac3d-f2730c00b2e4)

**Comment by cars10** [comment]
There are no changes in `8.12.2` that should result in this issue. Also i cannot reproduce it.

What does "unable to search" mean? What messsage do you get? Which OS?

**Comment by cars10** [comment]
Version `1.0.4` includes a debug console. Please

* right click anywhere
* hit "inspect element"

Then check the console and the network tab for errors or hints, thanks

**Comment by terzano** [comment]
No exceptions on the console. Only message is the insecure request. I don't think that is the issue.

![evue](https://github.com/cars10/elasticvue/assets/343932/5988e5db-23c0-4ada-acc6-24c9478ec4a3)

**Comment by cars10** [comment]
Search query time added in `1.0.5`, it shows the value of  `"took"`

**Comment by cars10** [comment]
Hey @terzano , i have implemented more logging in elasticvue desktop `1.0.5`. You can run it with `RUST_LOG=info ./elasticvue`, elasticvue will log every http request and the response status code. Maybe this helps debugging the issue?

**Comment by cars10** [comment]
Closed until more information is available or anyone is able to reproduce the issue.
