### ISSUE TITLE
[FEAT] - Footer should be sticky to bottom of screen

### ISSUE THREAD

**Issue by jeffreydwalter** [cars10/elasticvue#217]
When dealing with more than a handful of records and setting paging to be 100 or more, the footer is pushed off the screen. This sucks for a few reasons, but the main one is that the bulk deleting and paging controls are at the bottom of the very long page. This makes for a lot of unnecessary scrolling.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Open an index with more than a couple hundred records
3. Set paging to be 100 or more

**Comment by cars10** [comment]
You can enable the `sticky table header` option on the cog wheel near the table to limit the size of the scrolling window :) By doing so you can position the footer wherever you like.
