### ISSUE TITLE
索引文档数据量大的时候，筛选不起作用

### ISSUE THREAD

**Issue by 13462249457** [cars10/elasticvue#218]
1：问题描述
当索引的数据量大的时候通过控制台页面筛选不起作用，数据量小的时候是正常的，如下图：
100多个文档，数据量小时图如下：
![image](https://github.com/cars10/elasticvue/assets/40123216/a6cadb7b-ff25-4bab-aff0-32e893867c37)
7w+文档，数据量大的时候：
![image](https://github.com/cars10/elasticvue/assets/40123216/81cab596-502e-478e-89ca-8fb927c88fce)

**Comment by cars10** [comment]
Hey, sorry but i don't understand what you are trying to say. Google translate / deepl don't really help here. Can you explain your issue in english maybe?

**Comment by cars10** [comment]
Closed until i can understand what it is about
