### ISSUE TITLE
[FEAT] Document issue and solution accessing http-urls with HTTPS-Only Mode enabled in Firefox

### ISSUE THREAD

**Issue by cstsw** [cars10/elasticvue#220]
**Description**
After enabling HTTPS-Only Mode in Firefox I ran into an issue connecting to clusters that are only accessible via http. According to the console Firefox tried to upgrade those URLs to https and failed. I first added the cluster URLs to the HTTPS-Only exceptions but that didn't work. However, adding the moz-extension-url to those exceptions did resolve the issue.

![elasticvue-https-only-exception](https://github.com/cars10/elasticvue/assets/30345010/71f38823-72cf-4bf2-941b-20dfabbd7f57)

I suggest to document this somewhere in the wiki (e.g. in the FAQ).

**Comment by alaunay** [comment]
Had the same problem here, this did the trick ! Thanks !

**Comment by cars10** [comment]
Well, if you force everything to be https... everything will be https, including access to your cluster^^ The best way would be to actually `use` https for cluster access, but i guess this also works.

**Comment by alaunay** [comment]
I agree with your comment :) In our case it was our graylog ES, which is a standalone one running on localhost, until I asked myself "what's in this big index". So I looked for a phpmyadmin/adminer for ES, found your great piece... And just opened the ES to the network. That's where the https trouble began ;-) I'll look at adding SSL support to ES.

Thanks for this software !
