### ISSUE TITLE
[BUG] - special characters like % in index name don't work

### ISSUE THREAD

**Issue by marcohald** [cars10/elasticvue#221]
**Description**
Indices like "filebeat-8.10.2-%{[customer]}-merged4-2024.99" could not be opened or deleted
The Browser send a request like this when i click on the Index in the Indices tab `http://localhost:9200/filebeat-8.10.2-%%7B[customer]%7D-merged4-2024.99/_search`
Elasticsearch answers with a 404 and this
`
reason : "no such index [filebeat-8.10.2-%7B[customer]}-merged4-2024.99]"`
The Problem seems to be the % is not encoded but elasticsearch seems  to need that to be encoded
When I manually request it like that `http://localhost:9200/filebeat-8.10.2-%25%7B[customer]%7D-merged4-2024.99/_search` it works

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Create a index called "filebeat-8.10.2-%{[customer]}-merged4-2024.99"
2. Open elasticvue
3. Click on indices and then on the index named "filebeat-8.10.2-%{[customer]}-merged4-2024.99"

**Environment (please include the following information):**
* Elasticsearch version:  Opensearch 2.12.0
* Operating system: Windows 10
* Browser + version: Firefox 123.0.1
* Elasticvue version:  1.0.4-stable
* How are you running elasticvue? (docker, browser extension, web app): firefox extension

**Comment by cars10** [comment]
Hey, i am not able to even create an index with a name like that in any version of elasticsearch. Can you provide details on how to reproduce this?

**Comment by BlindB0** [comment]
Face the same problem.
I have index with "-%y-%m-%d" in name.  Fluentd made this by misconfig a long ago and I have to deal with it.
So I can push api requests with curl by "index-%25y-%25m-%25d" in url (substitute '%' by '%25'), but elasticvue cannot handle this index.

**Comment by cars10** [comment]
Fixed in `1.0.9`
