### ISSUE TITLE
Can you update metrics such as time taken for each single query like Kibana ?

### ISSUE THREAD

**Issue by vinhtruongol** [cars10/elasticvue#223]

**Comment by vinhtruongol** [comment]
I can access the performance metrics but for a single query, when changing indexing, how can i know that the new analyzers is better performance (time taken) than the previous one

**Comment by cars10** [comment]
Will be added in the next version
![image](https://github.com/cars10/elasticvue/assets/4118628/93a47606-4b22-475e-9156-12bf9f456f28)

**Comment by cars10** [comment]
Search query time added in `1.0.5`, it shows the value of  `"took"`
