### ISSUE TITLE
[BUG] - GLIBC_2.3x' not found (AppImage Linux)

### ISSUE THREAD

**Issue by Stef500** [cars10/elasticvue#224]
**Description**
Can't use AppImage with Linux Mint 20.2 (based on Ubuntu 20.04).

**Steps To Reproduce**
Launch AppImage in shell and here is the log:
"
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by elasticvue)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by elasticvue)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by elasticvue)
elasticvue: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libwebkit2gtk-4.0.so.37)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libwebkit2gtk-4.0.so.37)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libwebkit2gtk-4.0.so.37)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libwebkit2gtk-4.0.so.37)
elasticvue: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libwebkit2gtk-4.0.so.37)
elasticvue: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libwebkit2gtk-4.0.so.37)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libgtk-3.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libgdk-3.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libcairo.so.2)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libgio-2.0.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libgio-2.0.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libjavascriptcoregtk-4.0.so.18)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libjavascriptcoregtk-4.0.so.18)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libjavascriptcoregtk-4.0.so.18)
elasticvue: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libjavascriptcoregtk-4.0.so.18)
elasticvue: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libjavascriptcoregtk-4.0.so.18)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libglib-2.0.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libglib-2.0.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libglib-2.0.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libcrypto.so.3)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libcrypto.so.3)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libwpe-1.0.so.1)
elasticvue: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libWPEBackend-fdo-1.0.so.1)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libepoxy.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libsystemd.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libsystemd.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libsystemd.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libicuuc.so.70)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libicuuc.so.70)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libxml2.so.2)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libxml2.so.2)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libsqlite3.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libsqlite3.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libxslt.so.1)
elasticvue: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libwoff2dec.so.1.0.2)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libgcrypt.so.20)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libgstreamer-1.0.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libgstreamer-1.0.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libgstpbutils-1.0.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libopenjp2.so.7)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libwebp.so.7)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libenchant-2.so.2)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libgmodule-2.0.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libwayland-server.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libwayland-server.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libxkbcommon.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libpsl.so.5)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libgssapi_krb5.so.2)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libmount.so.1)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libmount.so.1)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libselinux.so.1)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libselinux.so.1)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/liblzma.so.5)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/liblzma.so.5)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libcap.so.2)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libunwind.so.8)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libunwind.so.8)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libdw.so.1)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libdw.so.1)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libgudev-1.0.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libevdev.so.2)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libdbus-1.so.3)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libdbus-1.so.3)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libXau.so.6)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libunistring.so.2)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libunistring.so.2)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libkrb5.so.3)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libkrb5.so.3)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libk5crypto.so.3)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libkrb5support.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libkrb5support.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libblkid.so.1)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libelf.so.1)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libudev.so.1)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libudev.so.1)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libbsd.so.0)
elasticvue: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_elastitEhBnQ/usr/lib/libmd.so.0)
"

**Environment (please include the following information):**
* Operating system: Linux Mint 20.2 (absed on Ubuntu 20.04)
* Browser + version: Chrome 123.0.6312.105
* Elasticvue version: 1.0.4 
* How are you running elasticvue? (docker, browser extension, web app): AppImage

Thanks

**Comment by cars10** [comment]
Hey @Stef500 , thanks for opening this issue :) 
Did you try to install or update glibc? It is a requirement of tauri, so i can not really work around it.

**Comment by Stef500** [comment]
> Hey @Stef500 , thanks for opening this issue :) 
> Did you try to install or update glibc? It is a requirement of tauri, so i can not really work around it.


Hi @cars10 thanks for your answer. However, it seems that I can't update glibc without updating the whole OS (which I can't do) cf.  https://ubuntuforums.org/showthread.php?t=2486771
Do you plan to build it for Ubuntu 20.04 please ?
Thanks in advance !

**Comment by cars10** [comment]
Hey @Stef500 , i am afraid that this is not possible. Tauri requires a newer version of glibc, see https://github.com/tauri-apps/tauri/issues/9039 - this would need a fix on tauris side of things. In the meantime you can always use elasticvue via the browser extensions, web app or self hosted (e.g. docker). Sorry for the inconvenience.

**Comment by FabianLars** [comment]
> Hey Stef500 , i am afraid that this is not possible. Tauri requires a newer version of glibc, see https://github.com/tauri-apps/tauri/issues/9039 - this would need a fix on tauris side of things. In the meantime you can always use elasticvue via the browser extensions, web app or self hosted (e.g. docker). Sorry for the inconvenience.

Hey, i just saw this issue linked in 9039. To be frank, what you said here is incorrect - and 9039 is about tauri v2.
The way Linux binaries and appimages work is basically that you have to compile them on the oldest platform you want to support. So for example to support ubuntu 20.04 (OP's version) you have to build on ubuntu 20.04 or below. You're currently building on ubuntu-latest which is 22.04 and in a few weeks/months 24.04.

This is not something we can easily (if at all) fix in Tauri itself even though we'd really love to.
