### ISSUE TITLE
[FEAT] Recover double click edit action

### ISSUE THREAD

**Issue by fernandomacho** [cars10/elasticvue#225]
In previous versions, double-clicking on a document opened its editing modal. In this version to edit a document you have to scroll to the right and click on the pencil. If the document has many attributes it is very inefficient.

**Comment by genkin-he** [comment]
+1

**Comment by cars10** [comment]
Actually this was changed due to feedback from the survey, many users complained that the could not copy data from the table without opening the edit modal, since it always opened with a single click (not double click). 

I will think about ways to improve this for both sides.

**Comment by fernandomacho** [comment]
Maybe the solution might be to put the buttons on the left, instead of the right? or add event on right click?

**Comment by realtydev** [comment]
+1

**Comment by cars10** [comment]
Out of curiosity, why is editing such a big usecase for you? In my experience you usually index data from an existing database or ingest logs. I have never worked with an elasticsearch deployment where i would manually edit documents.

**Comment by Yohann-Bethoule** [comment]
+1 too 

To answer your question @cars10 , my use case is that the documents indexed in my es indexes are quite big, so browsing its data using the horizontal scroll is quite tedious, while visualizing my documents in the modal with a json formatting is much more easy for me.

**Comment by PA-recomed** [comment]
+1
I just want to open the record and see the data.

**Comment by fernandomacho** [comment]
Open, view, copy information .... edit on error ....

**Comment by cars10** [comment]
I have just published `1.0.6`, you can **double click** a row to open the edit modal. It might take a while until the browser extensions are updated.
