### ISSUE TITLE
[BUG] - Viewing or editing document in index does not work

### ISSUE THREAD

**Issue by bosix** [cars10/elasticvue#227]
**Description**
After updating to v1.0.7 viewing or updating document data does not work anymore

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on Indices and open any index
3. double click a document to view or edit the document

**Screenshots**
![325687883-0ed75bbb-4729-4f85-8055-afa8a4630fdf.png](https://github.com/cars10/elasticvue/assets/26360670/9031b2f4-d190-47e1-b647-3f65da9567ee)

**Environment (please include the following information):**
* Elasticsearch version: 8.13.2
* Operating system: Ubuntu 22.04.4 LTS
* Browser + version: Vivaldi 6.6.3271.61
* Elasticvue version: 1.0.7
* How are you running elasticvue? (docker, browser extension, web app): docker container

**Additional context**
I've testet the same steps with elastic vue v1.0.6 and everything works with the older version.

**Comment by cars10** [comment]
This sounds like a caching issue on your side. I cannot reproduce any issues with 1.0.7 - do you still experience this?
