### ISSUE TITLE
[BUG] - Unable to install the Deb version on Ubuntu 24.04

### ISSUE THREAD

**Issue by pranavajk1** [cars10/elasticvue#228]
**Description**
Unable to install the Deb Version of the App on Ubuntu version 24.04

**Steps To Reproduce**
Error Received:
The following packages have unmet dependencies:
  elasticvue: Depends: libwebkit2gtk-4.0-37 but it is not installable

**Environment (please include the following information):**
* Elasticsearch version:
* Operating system: Ubuntu 24.04 (Linux Kernel: 6.8.7)
* Browser + version:
* Elasticvue version: 1.0.7
* How are you running elasticvue? (docker, browser extension, web app): Desktop App

**Additional context**
Anything else?

**Comment by cars10** [comment]
This is a requirement of tauri, see this issue: https://github.com/tauri-apps/tauri/issues/9662
