### ISSUE TITLE
[BUG] - cannot open documents in elasticsearch 8

### ISSUE THREAD

**Issue by StefanSa** [cars10/elasticvue#23]
**Description**
Hi Carsten,
suddenly the content of the index is no longer displayed, but that had worked before.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on search -> show

**Screenshots**
![no_index_show](https://user-images.githubusercontent.com/6105075/82643965-ccf15800-9c10-11ea-8ca5-132bdb170e45.png)

**Environment (please include the following information):**
* Elasticsearch version: 8.0
* Operating system: docker image
* Browser + version: chrome and firefox latest
* Elasticvue version: 0.22.0
* How are you running elasticvue: browser extension

**Comment by cars10** [comment]
Hi Stefan, thanks for reaching out. Elasticsearch 8 is not officially supported yet (see the Readme, right now i strife to support 5.6, 6.8 and 7.x).

However i obviously plan to support elasticsearch 8 so i will try to reproduce this issue. Can you point me to a download link for elasticsearch 8?

**Comment by StefanSa** [comment]
Carsten, you can simple run with this:
docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT

**Comment by cars10** [comment]
Fixed in `0.23.0`. Thanks again!
