### ISSUE TITLE
[BUG] - UI Issue in the Cluster Home Page

### ISSUE THREAD

**Issue by pranavajk1** [cars10/elasticvue#230]
**Description**
The Title or Cluster ID is too long it overshoots the card.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Open the home page of any clutser
3. The Cluster ID is overshooting the card

**Screenshots**
![Screenshot_20240505_114013](https://github.com/cars10/elasticvue/assets/114953548/8a7ddc1e-d090-41d4-acc0-02fcd91c4638)

**Environment (please include the following information):**
* Elasticsearch version: 
* Operating system: Fedora 40
* Browser + version: Firefox
* Elasticvue version: 1.0.7
* How are you running elasticvue? (docker, browser extension, web app): Browser Extension

**Additional context**
Anything else?

**Comment by cars10** [comment]
Fixed in `1.0.8`. Thanks!
