### ISSUE TITLE
[FEAT] Any plan to support multi-line scripts queries in REST section ?

### ISSUE THREAD

**Issue by davidfabreguette** [cars10/elasticvue#231]
**Description**
Support such query formatting :
```painless
{
    "query": {
        "bool": {
            "filter": [
            {
              "script": {
                "script": {
                  "source": """
                     String myvar = "any var";
                     return true;
                  """,
                  "lang": "painless"
                }
              }
            },
        }   
    }
}
```

**The feature is similar to kibana dev tools**
<img width="823" alt="Capture d’écran 2024-05-07 à 16 40 41" src="https://github.com/cars10/elasticvue/assets/749900/749f4b8b-adbe-4176-997b-d0a293cff68c">

**Comment by cars10** [comment]
This is currently not planned. Using triple quotes for multiline scripts is a kibana feature, these scripts are converted by kibana to single line scripts and then sent to elasticsearch.
