### ISSUE TITLE
[BUG] - An error occurred when clicking on the shards tabs 

### ISSUE THREAD

**Issue by drlifeL** [cars10/elasticvue#232]
**Description**
When a closed index exists in my ES cluster, an error occurs when accessing the shard tab.

**Steps To Reproduce**
List the steps to reproduce your problem:
1.Open elasticvue
2.Close any ES index
3.Click shard tab.

**Screenshots**
<img width="606" alt="image-20240509232529894" src="https://github.com/cars10/elasticvue/assets/37680485/fc54116c-8a59-4320-a799-a48b5530f044">

**Environment (please include the following information):**
* Elasticsearch version: 6.8.3
* Operating system: MacOS 14.1.1
* Browser + version:  chrome 124.0.6367.93
* Elasticvue version: 1.0.6-stable
* How are you running elasticvue? (docker, browser extension, web app): browser extension

**Additional context**
This error is currently mandatory in es 6.8.3, and I did not reproduce this error in 7.16.2 .

**Comment by cars10** [comment]
i cannot reproduce this. Do you have more information? Close shards work as expected with every version of elasticvue.
