### ISSUE TITLE
[FEAT] - confirm shard relocation

### ISSUE THREAD

**Issue by coola007** [cars10/elasticvue#236]
Hi: 
chrome ext :
Using shard reroute operations, clicking on a shard cannot be canceled, only refreshing the page works.

 Reroute operations do not provide prompts, and making a mistake can be extremely risky
 
 So this action is very warning...
This operation needs to be handled with great care and requires prompts; otherwise, the risk of making a mistake is very high.

**Comment by cars10** [comment]
Fixed in `1.0.8`. Thanks!
