### ISSUE TITLE
[BUG] - All shards not visible in Shards TAB when shard count is high

### ISSUE THREAD

**Issue by luvk1412** [cars10/elasticvue#237]
**READ BEFORE OPENING AN ISSUE**
Before you submit an issue please try to reset elasticvue and see if you can reproduce the problem.
To reset please click `Disconnect and reset` in the footer, this will reset all your saved filters and you have to reconnect to your cluster.
Proceed and open an issue if your problem persists.

**Description**
I have 180 primary shards with 1 replica across 2 nodes. When i go to shards tab in Elastic vue i am not able to see all the shards on a particular node. There is only single row of shards visible in front of each node and number of shards visible in that row depend on the width of the window of elastic vue app. I was expecting either the shards would wrap according to widthof window or it would be horizontally scrollable, neither of which is the case currently.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Create an elastic search cluster with 180 primary shards and add it to elastic vue
2. Open elastic vue and got shards tab to observe above issue

**Screenshots**
Number of shards visible with high window width
![Screenshot 2024-05-28 at 6 38 02 PM](https://github.com/cars10/elasticvue/assets/11024840/640d1dd5-ee64-4b06-9393-b5bff0454b07)

Number of shards visible with less window width
![Screenshot 2024-05-28 at 6 37 52 PM](https://github.com/cars10/elasticvue/assets/11024840/574f7a6f-76b5-4736-abf0-38561554da76)

**Environment (please include the following information):**
* Elasticsearch version: 8.13.4
* Operating system: Mac OS
* Browser + version: Google Chrome ( Version 125.0.6422.77 (Official Build) (arm64))
* Elasticvue version: 1.0.8-stable
* How are you running elasticvue? (docker, browser extension, web app): I have tried above on both extension as well as mac os native app. Both show same issue.

Anything else?

**Comment by cars10** [comment]
Fixed in `1.0.9`
