### ISSUE TITLE
[FEAT]Download file as excel / csv

### ISSUE THREAD

**Issue by majiayu000** [cars10/elasticvue#238]
Have you considered adding  an excel download?

**Comment by cars10** [comment]
What exactly do you want to download? Please provide more information.

**Comment by majiayu000** [comment]
Just download the es index content as a excel but not json.

**Comment by cars10** [comment]
This is currently not planned. Your documents can have varying amounts of complexity and there is no straight forward way to print these in a 2D format like excel.
