### ISSUE TITLE
[BUG] - Sorting indices by storage doesn't take units into consideration

### ISSUE THREAD

**Issue by qbaze** [cars10/elasticvue#24]
**Description**
On the 'Indices' view sorting by 'Storage' column doesn't take units into consideration, just numbers.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue 
2. Click on INDICES in the upper menu 
3. Click on Storage column name to sort

**Screenshots**
![image](https://user-images.githubusercontent.com/5493094/83792983-255a3800-a69c-11ea-82c0-ac6e75ac0f48.png)

**Environment (please include the following information):**
* Elasticsearch version: 5.6.10
* Operating system: centos 7
* Browser + version: firefox 77.0.1 (64-bit)
* Elasticvue version: Elasticvue 0.22.0
* How are you running elasticvue? browser extension

**Additional context**
n/a

**Comment by cars10** [comment]
Thanks for reporting this issue, i will see what i can do to fix that.

**Comment by cars10** [comment]
Fixed in `0.23.0`. Thanks again!
