### ISSUE TITLE
Unable to batch delete indexes[BUG] - SHORT DESCRIPTION OF THE BUG

### ISSUE THREAD

**Issue by lyanantx** [cars10/elasticvue#240]
**READ BEFORE OPENING AN ISSUE**
Before you submit an issue please try to reset elasticvue and see if you can reproduce the problem.
To reset please click `Disconnect and reset` in the footer, this will reset all your saved filters and you have to reconnect to your cluster.
Proceed and open an issue if your problem persists.

**Description**
Please describe your problem here.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on ...
3. ...

**Screenshots**

**Environment (please include the following information):**
* Elasticsearch version:
* Operating system:
* Browser + version:
* Elasticvue version:
* How are you running elasticvue? (docker, browser extension, web app):

**Additional context**
Anything else?

**Comment by cars10** [comment]
Please use the issue template to provide more details about your issue.
