### ISSUE TITLE
[BUG] - Elasticvue uses the old templates API

### ISSUE THREAD

**Issue by aidin-gh** [cars10/elasticvue#242]
**Description**

The Elasticvue is using the deprecated `_template` API. It should use the new `_index_template` API.

See: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates-v1.html

**Steps To Reproduce**

I installed the Firefox extension and checked the developer's console. The `network` tab shows that it's calling the old API.

I also tried the Linux client. I can't see what API it's calling, but I can check that it doesn't show the templates I have.

**Screenshots**

![screenshot](https://github.com/cars10/elasticvue/assets/38443968/7684a2c9-7449-413f-b42b-b34901da77d4)

**Environment (please include the following information):**
* Elasticsearch version: 8.14.1
* Operating system: Gnu/Linux Ubuntu 24.04
* Browser + version: Firefox 127.0.2
* Elasticvue version: 1.0.8-stable
* How are you running elasticvue? (docker, browser extension, web app): Browser extension & Linux Image

**Comment by cars10** [comment]
Fixed in `1.0.9`
