### ISSUE TITLE
[BUG] - Test connection fails due to closed index

### ISSUE THREAD

**Issue by vimt** [cars10/elasticvue#243]
**Description**
When attempting to add a connection and click on "test connection," I encounter a `400 Bad Request` error with the message "Can't connect to your cluster. Please make sure that." After investigation, I discovered that the `/_search` endpoint is being called, and the error is due to an `index_closed_exception`. One of the indices in my cluster is closed, which causes the test connection to fail.

It might be more robust to use a different endpoint for testing the connection that doesn't depend on the state of the indices, such as `/_cluster/health`.

**Steps To Reproduce**
1. Open elasticvue.
2. Add a new connection.
3. Click on "test connection."
4. Observe the `400 Bad Request` error.

**Screenshots**
<img width="966" alt="image" src="https://github.com/user-attachments/assets/80a0e4b8-9916-4a34-a113-c5d85bdb3a27">

**Environment (please include the following information):**
* Elasticsearch version: 6.8.3
* Operating system: Mac OSX
* Browser + version: 126.0.6478.127
* Elasticvue version: Elasticvue 1.0.9-stable
* How are you running elasticvue? (docker, browser extension, web app): browser extension

**Additional context**
The specific error message returned is:
```
{
    "error": {
        "root_cause": [
            {
                "type": "index_closed_exception",
                "reason": "closed",
                "index_uuid": "G1ni26YnTK6praJgoFquvA",
                "index": "foo_index"
            }
        ],
        "type": "index_closed_exception",
        "reason": "closed",
        "index_uuid": "G1ni26YnTK6praJgoFquvA",
        "index": "foo_index"
    },
    "status": 400
}
```
This indicates that the test connection functionality might need to be adjusted to avoid relying on `/_search`, as closed indices can cause false negatives.

**Comment by cars10** [comment]
I cannot reproduce this issue. Calling the /search endpoint should not fail because any indices are closed. Do you have more information that might be helpful?

![image](https://github.com/user-attachments/assets/c7a30bbd-d239-4649-9707-5c83f647f403)

**Comment by vimt** [comment]
Thank you for your quick response.

After further investigation. I set up a Docker version of Elasticsearch and confirmed that the problem does not occur under normal circumstances. The issue only occurs when call the endpoint `/_search?expand_wildcards=all` and there is a closed index.

It seems that the Elasticsearch setup in my company might have some issues causing this behavior. I apologize for the confusion and any inconvenience this may have caused. 😅

**Comment by s-fleck** [comment]
Hmm it seems we have the same problem with Elasticsearch 7.17.12. I cannot provide any additional info to OP, but I'm getting the same error for a closed index.

**Comment by s-fleck** [comment]
We have the same problem with Elasticsearch 7.17.12. Test Connection fails with the same error as OP described, but connecting to the cluster works.
