### ISSUE TITLE
[BUG] - After 1.0.9 release column width not fixed on Indices tab. 

### ISSUE THREAD

**Issue by abishekhkamath** [cars10/elasticvue#245]
**Description**
Alias column width is not fixed in the latest release. So to reach  shards, Docs, settings column one has to scroll horizontally to go past entire alias list. 
1.0.8 would just show couple of aliases then add ...

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Create a index
3. Create 100s of alias on a index
4. Check the Indices tab

**Screenshots**
<img width="1788" alt="elasticvue" src="https://github.com/user-attachments/assets/5aa71a0c-ecfe-4b69-81b7-4c31446ec2fc">

**Comment by cars10** [comment]
Thanks, good catch. Fixed in `1.0.10`.

**Comment by abishekhkamath** [comment]
Thank you @cars10 for quickly resolving this
