### ISSUE TITLE
[BUG] - 403 during connection

### ISSUE THREAD

**Issue by slgithuba** [cars10/elasticvue#246]
I encountered error 403 when connecting to elastic search. Upon checking the console, I found that it had been added
origin:chrome-extension://hkedbapjpblbodpgbajblpnlpenaebaa
<img width="699" alt="image" src="https://github.com/user-attachments/assets/713ab6ba-eb29-4170-88c5-2d6477a67876">

**Comment by cars10** [comment]
Please add more information:

**Environment (please include the following information):**
* Elasticsearch version:
* Operating system:
* Browser + version:
* Elasticvue version:
* How are you running elasticvue? (docker, browser extension, web app):
* Does the cluster use SSL?
* Is you cluster protected by username & password?

**Comment by cars10** [comment]
Closed until more info is provided.
