### ISSUE TITLE
[FEAT] Support displaying aggregation in the search interface

### ISSUE THREAD

**Issue by Ghpapa** [cars10/elasticvue#247]
**Description**
When searching with aggs, it shows not only the hits but also the content in the aggregation.

**Comment by Basssiiie** [comment]
Maybe it's possible to show it in some form of collapse tree view? One node per aggregate, nested aggregates are nested nodes under the parent aggregate. Nodes with buckets could become a small table with key + doc count. 🙂

I'm using the ElasticVue browser extension and now when working with aggregates I just have the network tab open to review the response there.

**Comment by cars10** [comment]
I will add a json view for aggs in the next version as a first step. Not pretty, but you can see them.

<img width="1215" height="1071" alt="Image" src="https://github.com/user-attachments/assets/c29fde9f-228e-4f58-8379-6212a0391fae" />

<img width="1200" height="1079" alt="Image" src="https://github.com/user-attachments/assets/1dac731b-79b3-42be-910b-655968157da2" />

**Comment by Basssiiie** [comment]
That'd be great, thank you for your quick response! 😄

**Comment by cars10** [comment]
This was added in `1.13.0`.
