### ISSUE TITLE
Credentials storage

### ISSUE THREAD

**Issue by ArturMarszalek** [cars10/elasticvue#248]
Hello,

It’s a great tool, very useful.

I cannot find information about storing credentials for my Elasticsearch service. I use a Chrome extension where my password and user are saved (locally on my PC). Is that secured?

I could not find that information on the website or GitHub.

**Comment by cars10** [comment]
Hi, currently your credentials are saved **in plain text** in local storage. So if someone has access to your computer he might be able to retrieve them.
