### ISSUE TITLE
path-prefix and URI combination

### ISSUE THREAD

**Issue by kumgaurav** [cars10/elasticvue#249]
**Description**
My elastic search is behind the load balancer and needs path-prefix to connect. I tried using URI and it's not working.

We do not have kibana any more so hard to provide the evidence for it. I can connect through springboot and it allows me using path-prefix.

**Comment by cars10** [comment]
Elasticvue supports elasticsearch clusters that use a subdirectory out of the box. You can just use the full path as uri in elasticvue, e.g.

![image](https://github.com/user-attachments/assets/5d3db18b-4311-413b-ba58-62b6826f5071)
![image](https://github.com/user-attachments/assets/d570c13b-0d53-448d-9fd2-86fd208b3c2b)

This works as expected. Please reopen if this does not work for you, you might have a different issue then.
