### ISSUE TITLE
[FEAT]Index selection questions

### ISSUE THREAD

**Issue by AiTian1211** [cars10/elasticvue#252]
After selecting an index, when I query other indexes again, the previously selected index state is not cleared, or when I turn the page after selecting an index, the previously selected index state is not cleared, for example, I inadvertently selected all the indexes filtered in the production environment, but when I delete the other indexes selected by querying, the previously unintentionally selected index will be deleted.

My question is whether it is a query or a page turn that clears all previous operations, such as index selection?

**Comment by cars10** [comment]
Hi :) Not immediately clearing indices is a feature. Imagine that you want to do multiple operations on a set of indices and would have to select them all over again. 

If you are unsure if you still have some indices selected (possibly on a different page), there are two places in the ui where you can check:

![image](https://github.com/user-attachments/assets/2cee1bd2-23d4-4767-819e-e706933e44fe)

* In the top left, in the table, the main checkbox will include a dash, indicating that some rows are selected
* In the bottom left, near the bulk operations, you can see how many indices are selected

The simplest way to clear the current selection is to click **twice** on the checkbox in the top left in the table header. Adding a dedicated "clear" button near the bulk operations might be a good idea though.
