### ISSUE TITLE
[FEAT] Support Auto Theme

### ISSUE THREAD

**Issue by pallxk** [cars10/elasticvue#255]
**Description**
We have light and dark themes, and it would be better if we can have a theme option that automatically matches system theme (light or dark).

**The feature is similar to..**

* [GitHub Theme Mode](https://github.com/settings/appearance)
* [Google Search Dark Theme options](https://www.google.com/preferences#tabVal=1)

**Comment by pallxk** [comment]
More on current status of light/dark theming:
* as long as a theme (light/dark) is never selected explicitly, the theme can be changed automatically on reload; once theme is toggled manually, no more auto light/dark theming;
* light/dark theme toggling happens only on reload, not when OS preference changes.

So to be precise, the feature requests are:
* allow auto/light/dark theme selection;
* if auto is selected, change theme on OS preference updates.

**Comment by cars10** [comment]
To implement this for the desktop we are blocked by https://github.com/tauri-apps/tauri/pull/10210/files

**Comment by cars10** [comment]
> To implement this for the desktop we are blocked by https://github.com/tauri-apps/tauri/pull/10210/files

This is merged in tauri, once 2.0 is released we can add this in elasticvue.

**Comment by cwsqer006** [comment]
tyhju

**Comment by cars10** [comment]
Will be supported in the next version.
