### ISSUE TITLE
[FEAT]Show ES version running on node

### ISSUE THREAD

**Issue by TinLe** [cars10/elasticvue#260]
**Description**
In the NODES display, it would be very useful to know the current ES version running on each node.

Use case is when a cluster is going through a rolling update from one version to another. Very useful to know which node has been upgraded.

This is also useful for verifying if all nodes are running the same version.

**The feature is similar to..**
None

**Additional context**
This feature is very helpful for migration, diagnosing issues.

**Comment by cars10** [comment]
Added in `1.0.11`.
