### ISSUE TITLE
[FEAT]  能否支持Elastic 8.0 的SQL查询

### ISSUE THREAD

**Issue by alex-dengx** [cars10/elasticvue#265]
Elastic supports querying through SQL, which is very convenient for querying structured data. I wonder if there are plans to support SQL queries, such as the following search statement:
 
GET /_sql?format=txt 
{
  "query": """
  SELECT process_path, process_sha, path from file_read_logs where process_path like '%firefox.exe%' and machine_name='PC2FPDLC'
  """
}

**Comment by cars10** [comment]
Hello, nothing should stop you from using sql. E.g.:

![image](https://github.com/user-attachments/assets/e280a8c7-4a35-4111-95a4-3f3463a59980)

**Comment by alex-dengx** [comment]
你的邮件我已经收到。
