### ISSUE TITLE
[BUG] - Autocapitalizing basic auth and cluster name

### ISSUE THREAD

**Issue by woodcockjosh** [cars10/elasticvue#266]
**Description**
When adding a cluster, the first character in the cluster name is auto capitalized. Same thing with the username when specifying basic auth. This is really annoying because capitalizing the first letter should not happen for the cluster name because its a preference. It definitely should not happen for the username because the username is case sensitive. 

**Steps To Reproduce**
1. Create a new cluster
2. Enter mycluster
3. See that mycluster is changed to Mycluster
4. Enter basic auth username admin
5. See that uername is changed to Admin

**Environment (please include the following information):**
* Elasticsearch version: N/A
* Operating system: macos arm
* Browser + version: N/A
* Elasticvue version: 1.0.12-stable
* How are you running elasticvue? (docker, browser extension, web app): Desktop app

**Comment by cars10** [comment]
Hey @woodcockjosh , elasticvue does not do that. This seems to be a feature of your mac, i am not sure if i can disable it. I will check.

**Comment by cars10** [comment]
This is a setting in your mac.
![image](https://github.com/user-attachments/assets/33bd1e01-a1a4-4975-9490-64db1b3bbf71)
