### ISSUE TITLE
[FEAT] Date math in index names

### ISSUE THREAD

**Issue by snap87** [cars10/elasticvue#267]
**Description**
The index name is resolved into the desired index, but no search is carried out on it, although the results are found through the REST menu.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on Search
3. My search is: <kuber-{now/d}>  index.pattern is <kuber-{now/d}>.

**Screenshots**
![e1](https://github.com/user-attachments/assets/d9088923-025d-41be-bd5a-5aec4ad4715f)
![e2](https://github.com/user-attachments/assets/a450456e-ed4f-4847-b935-beb433450c8a)

**Environment**
Opensearch version: 2.16
 Operating system: Pop OS
 Browser + version: Firefox 132
* Elasticvue version: 1.0.12-stable browser extension

**Comment by cars10** [comment]
Datemath in index names is currently not supported. For now you have to escape the entities manually, e.g. `%3Ckuber-%7Bnow%2Fd%7D%3E`

**Comment by cars10** [comment]
Date math in index names is now supported in elasticvue `1.2.0`.
