### ISSUE TITLE
[BUG] - Can't connect es by elasticvue desktop

### ISSUE THREAD

**Issue by Xyq777** [cars10/elasticvue#269]
**Description**
I can successfully connect in the web application, but cannot connect in the desktop client, even though both use the same configuration

**Steps To Reproduce**
1. Open elasticvue
2. start es in docker by using the official tutorial
 `docker run --name es01 --net elastic -p 9200:9200 -it -m 1GB docker.elastic.co/elasticsearch/elasticsearch:8.16.0`
3.get password and import the Certificate
4.try to connect in elasticvue desktop

**Screenshots**
in web
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/5854b65a-5954-46e0-b237-757eeb49e0da">
in desktop
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/e8b78296-6e0c-49b7-9cc9-dc17aa704c13">
use es api
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/eec29b05-ab51-4f15-85b4-39e40574aa33">

**Environment :**
* Elasticsearch version: 8.16.0
* Operating system: macos 14.3
* Browser + version: arc1.67.2
* Elasticvue version:1.0.12-stable
* How are you running elasticvue? (docker, browser extension, web app): desktop

**Additional context**
Anything else?

**Comment by cars10** [comment]
Hey @Xyq777 , do you still have this issue? Did you check your network settings? Maybe your Mac blocks network access.

**Comment by Xyq777** [comment]
Sorry, you’re right 😭. I realized that my proxy was intercepting requests sent to localhost. After disabling the proxy, everything worked fine. It seems to be the first time I’ve encountered this condition… Previously, my proxy doesn’t handle local requests.
