### ISSUE TITLE
[BUG] - Ctrl+q closes Elasticue even if it is not the currently-focused window

### ISSUE THREAD

**Issue by arcanemachine** [cars10/elasticvue#273]
**Description**
Pressing Ctrl+q closes Elasticvue even if another window is currently focused.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Open another window
3. Press Ctrl+q to close that window
4. Elasticvue closes

**Screenshots**
N/A

**Environment (please include the following information):**
* Elasticsearch version: 7.17.16 (Not relevant to bug)
* Operating system: Xubuntu 24.04.1 LTS
* Browser + version: N/A
* Elasticvue version: 1.1.0
* How are you running elasticvue? (docker, browser extension, web app): Running from AppImage executable

**Additional context**
N/A

P.S. Thanks for Elasticvue, it is excellent.

**Comment by cars10** [comment]
Fixed in `1.1.1`
