### ISSUE TITLE
[BUG] - CANT OPEN ELASTICVUE FOR WINDOWS

### ISSUE THREAD

**Issue by pbj0718** [cars10/elasticvue#274]
**READ BEFORE OPENING AN ISSUE**
Before you submit an issue please try to reset elasticvue and see if you can reproduce the problem.
To reset please click `Disconnect and reset` in the footer, this will reset all your saved filters and you have to reconnect to your cluster.
Proceed and open an issue if your problem persists.

**Description**
Windows system version: win11 23h2(os 22631.4460), when i open elasticvue v1.1.0, it cant work and close after five seconds

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue.exe for version v1.1.0
2. after 5 senconds it will close
3. try again you will get the same result

**Screenshots**

**Environment (please include the following information):**
* Elasticsearch version:v1.1.0
* Operating system:windows 11 23h2(os 22631.4460)
* Browser + version:
* Elasticvue version:
* How are you running elasticvue? (docker, browser extension, web app):

**Additional context**
sry my english is not good,hope you can resolve this problem as soon as possible

**Comment by cars10** [comment]
Hey @pbj0718 , sadly i cannot reproduce your issue. You said that it takes about 5 seconds until it closes - did you try to reset elasticvue in this timeframe? Maybe this solves your issue.

**Comment by pbj0718** [comment]
may be my operation is wrong,and can I ask how to reset elasticvue in this timeframe? I try to uninstall and download again,it cant work normal,and i cant operate after open elasticvue until it close,may i lose some necessary componet?

**Comment by cars10** [comment]
Did you install elasticvue with the .msi installer, or did you download the .exe from the releases directly?

**Comment by pbj0718** [comment]
i try the method you said but cant open elasticvue and make it work,i think my system have some problem,i try to fix it,thx
