### ISSUE TITLE
[BUG] - Cannot launch desktop app with 1.1.2

### ISSUE THREAD

**Issue by sylvainmetayer** [cars10/elasticvue#277]
**Description**

Since the 1.1.2 version, I cannot launch elasticvue on my Linux workstation (Fedora 40). I only have a blank screen with an error message in the console when I launch the AppImage : `Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...`

The bug is not present in the `1.0.12` version.

**Steps To Reproduce**

List the steps to reproduce your problem:
1. Open elasticvue

**Environment (please include the following information):**
* Elasticsearch version: 8.14
* Operating system: Fedora 40
* Browser + version: Gnome shell 46.7
* Elasticvue version: 1.1.2
* How are you running elasticvue? (docker, browser extension, web app): AppImage

**Comment by cars10** [comment]
Thats weird, thanks for reporting. I will try to replicate the issue

**Comment by cars10** [comment]
Can you try the binary instead of the AppImage to see if this makes a difference?

https://github.com/cars10/elasticvue/releases/download/v1.1.2/elasticvue

**Comment by cars10** [comment]
Just be aware that the binary cannot offer automatic updates (like the appimage). I will still try to replicate and fix the issue in the next few days.

**Comment by cars10** [comment]
@sylvainmetayer can you please try the appimage from this archive? https://github.com/cars10/elasticvue/actions/runs/12439267788/artifacts/2350584163 
i tried changing some dependency versions, might help.

**Comment by cars10** [comment]
I have released version `1.2.0` that should fix this.

**Comment by sylvainmetayer** [comment]
This is now working with this version, thanks !
