### ISSUE TITLE
[FEAT]Could you provide an offline browser extension? Thanks a lot

### ISSUE THREAD

**Issue by shangxiazuoyou** [cars10/elasticvue#279]

**Comment by cars10** [comment]
The browser extension does not require an internet connection. What exactly are you trying to do?

**Comment by cars10** [comment]
Please re-open if you have more information on your issue.

**Comment by shangxiazuoyou** [comment]
Hello, the reason is that our development environment is offline!

**Comment by cars10** [comment]
So what you need is a direct download of the browser extension to install it manually (instead of downloading through the addon store)?

**Comment by shangxiazuoyou** [comment]
Yes! thanks again.

**Comment by cars10** [comment]
You can clone the repo and run: `make build_browser_extensions` this will build the browser extensions in `./artifacts`. You will need a working docker environment because it is built in a docker container.

I will see if i can also upload the archives in the future to the releases.

**Comment by cars10** [comment]
Starting from `1.4.0`, the browser extensions are also uploaded to the releases: https://github.com/cars10/elasticvue/releases 
Altough i do not recommend to install them this way. Use your browsers addon store whenever you can.
