### ISSUE TITLE
[BUG] - Closed index will cause INDICES table blank

### ISSUE THREAD

**Issue by debuggings** [cars10/elasticvue#28]
**Description**
Closed index will cause INDICES table blank.
The browser console
`TypeError: Expected a finite number, got number: NaN`

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on `INDICES` tab
3. Select one index and click `Close Index` 
4. Refresh page(Refresh button cannot reproduce)
5. Indices table will be blank

**Screenshots**
![Browser Console error](https://user-images.githubusercontent.com/668404/86509675-37a2cf80-be1c-11ea-95b4-038b777387c2.png)
![Actual indices XHR response](https://user-images.githubusercontent.com/668404/86509691-6456e700-be1c-11ea-89d5-4ad041b9bfad.png)

**Environment (please include the following information):**
* Elasticsearch version: 7.4.2
* Operating system: MacOS 10.12
* Browser + version: Firefox 77.0.1 
* Elasticvue version: Elasticvue 0.23.0
* How are you running elasticvue? (docker, browser extension, web app):  Firefox extension.

**Additional context**
When an Index is closed, it's `store.size` will be null.
I think we should check if `value` is NaN [here](https://github.com/cars10/elasticvue/blob/285d5bb75fd44b6fd05add13c5b8f8d9f827d2a6/src/models/ElasticsearchIndex.js#L31)

**Comment by cars10** [comment]
Thank you for  the detailed bug report! I will fix this issue ASAP.

**Comment by cars10** [comment]
Fixed in `0.23.1`
