### ISSUE TITLE
[BUG] - too many bugs

### ISSUE THREAD

**Issue by hummingsoul** [cars10/elasticvue#280]
Have you tested this button click?
![mmexport1735104147638](https://github.com/user-attachments/assets/693aa368-eb38-4071-a2b4-c445959534c8)

Why does this input box have an autocomplete function? But the backspace key can't delete the value in it
![mmexport1735104152092](https://github.com/user-attachments/assets/8db6d12c-9cb5-469f-bd0c-235fae068789)

Why do these function buttons need to drag the scrollbar to come out?
![mmexport1735104156094](https://github.com/user-attachments/assets/50116313-1d11-4537-bf11-2c877a496d38)

The input box is filled with a historical value, but is the result searched by that historical value?
![mmexport1735104159950](https://github.com/user-attachments/assets/363826c7-00c6-4912-a89d-2c19cb3ffaa1)

Input fields are sometimes not editable........

**Comment by cars10** [comment]
@hummingsoul again: please fill out the issue template. I **need** to know your version of elasticsearch, elasticvue, operating system, etc - otherwise i cannot try to reproduce your issue.

**Comment by cars10** [comment]
Please use the issue template, as i cannot reproduce your isuses. I need information about your environment.

![image](https://github.com/user-attachments/assets/92a1358e-4aa8-4939-aba2-c6438c53d333)
![image](https://github.com/user-attachments/assets/6120d912-ba11-40e3-b55a-1574a5b38158)
