### ISSUE TITLE
[BUG] -Empty record in show detail

### ISSUE THREAD

**Issue by MB3r9** [cars10/elasticvue#29]
**Description**
Id the id of a record contains a forward slash (/) the show window is emtpy, always contains 'null'

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on search
3. Double click on a record with a '/' in the id

**Environment (please include the following information):**
* Elasticsearch version: 7.8
* Operating system: Windows 10
* Browser + version: Chrome
* Elasticvue version: 0.23.1
* How are you running elasticvue? (docker, browser extension, web app): docker

**Comment by cars10** [comment]
Thank you for the detailed bug report! I can reproduce the issue and will look into it ASAP.

**Comment by cars10** [comment]
Fixed in version `0.25.0`. Thanks again
