### ISSUE TITLE
[FEAT] CRUD operations while browsing data (Similar to Dejavu) 

### ISSUE THREAD

**Issue by rgb-panda** [cars10/elasticvue#30]
**Description**
So far Elasticvue has been my favorite ElasticSearch GUI, however the only feature I am missing which exists in Dejavu is the ability to create fields and update them while browsing. 

This is extremely useful when you're going through your data and want to categorize them by filling out the value for another field.

**The feature is similar to..**

Dejavu supports CRUD operations while browsing the data
https://github.com/appbaseio/dejavu

**Comment by cars10** [comment]
Thanks for the suggestion! I will prioritize this feature and see what i can do.

**Comment by cars10** [comment]
This will be implemented in the upcoming 1.0 beta.
