### ISSUE TITLE
[BUG] - Reletive path

### ISSUE THREAD

**Issue by dlsmlss** [cars10/elasticvue#31]
**Description**
Pathes hardcoded

**Steps To Reproduce**
I would like to run Elasticvue on site subfolder - https://subdomain.domain.com/elasticvue/

```
...
    location /elasticvue/ {
        alias /var/www/elasticvue/dist/;
        try_files $uri $uri/ /index.html?$args;
    }
...
```
And with this configuration many 404 errors when trying to access https://subdomain.domain.com/elasticvue/ cause links from index.html go https://subdomain.domain.com/assets/... and not to https://subdomain.domain.com/elasticvue/assets/...

**Screenshots**
Not needed.

**Environment (please include the following information):**
* Elasticsearch version: current
* Operating system: centos
* Browser + version: any
* Elasticvue version: current
* How are you running elasticvue? (docker, browser extension, web app): host assets on my own

**Comment by cars10** [comment]
Thanks! I have fixed the bug on the `develop` branch. You can use it right now or wait for the release of the next version. 

When you want to host elasticvue with a subdirectory then you need to add an environment variable to your build process:
```
VUE_APP_PUBLIC_PATH=/elasticvue/ yarn build
```

You also have to adjust your nginx config, for example:
```
server {
    listen 80;
    server_name _;

    root /var/www/elasticvue/dist;
    location ^~ /elasticvue {
        alias /var/www/elasticvue/dist;
        try_files $uri $uri/ /index.html?$args;
    }
}
```

**Comment by dlsmlss** [comment]
Thanks Carsten! Works as expected.
