### ISSUE TITLE
Allow TLS connections to ES

### ISSUE THREAD

**Issue by tmegow** [cars10/elasticvue#32]
**Description**
Please build support for TLS and mTLS connections to ES.

Currently https connections to ES result in:

![image](https://user-images.githubusercontent.com/10726968/88206704-b4a3b680-cc1c-11ea-9215-81aafee48eb2.png)

```
$ curl -ks https://localhost:9202
{
  "name" : "my-cluster.default.svc.cluster.local",
  "cluster_name" : "my-cluster",
  "cluster_uuid" : "J_ABE80yTBmd7jeH_9qpGw",
  "version" : {
    "number" : "7.0.1",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "e4efcb5",
    "build_date" : "2019-04-29T12:56:03.145736Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.7.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by cars10** [comment]
This is not an error in elasticvue but in your browser. 
It seems like you are using a self signed certificate. You browser does not trust it so it does not allow elasticvue to make any requests to your cluster. There are multiple ways to fix this problem:

1. Only use certificates created by a trusted CA (for example [letsencrypt](https://letsencrypt.org/))
2. Import your CA into the browsers certificate store
3. Simply bypass the error temporarily by entering https://localhost:9200 in your browser and clicking "Proceed to localhost (unsafe)". This way the browser will trust the certificate for your current session and you can also use elasticvue.

I will add this information to the readme.
