### ISSUE TITLE
Possibility to store urls to many instances of Elasticsearch

### ISSUE THREAD

**Issue by Celtir** [cars10/elasticvue#35]
Would it be possible to include an option for Chrome Extention to store and switch between different indexes?
It is often that many instances of ElasticSearch are present (for example dev and production) and it would be great if there was an easy way to switch between them.

**Comment by cars10** [comment]
Hi, thanks for using elasticvue. 

> to store and switch between different **indexes**?

Do you want to switch between different **indexes** or different **instances** (e.g. localhost:9200 and your.prod:9200)?

**Comment by Celtir** [comment]
Ah yes, instances please.

**Comment by cars10** [comment]
Thanks, i quite like the idea of having multiple clusters configured with an easy way to switch between them. I will see what i can do!

**Comment by Celtir** [comment]
Thank you a lot 💯

**Comment by cars10** [comment]
Hey @Celtir , i am currently working on this feature. Do you think something like this would work?
![image](https://user-images.githubusercontent.com/4118628/93717945-36f71b00-fb79-11ea-933b-f471a143febe.png)

I plan to replace the cluster information plain text in the navbar with the menu that you can see on the screenshot.

**Comment by Celtir** [comment]
It looks great!

**Comment by cars10** [comment]
Added in `0.30.0`. Sorry that it took so long!

**Comment by mabzzz** [comment]
Thank you very much :+1:
