### ISSUE TITLE
Help wanted: Elasticvue needs a new name

### ISSUE THREAD

**Issue by cars10** [cars10/elasticvue#36]
Elasticvue needs a new name, because "elastic" is a registered trademark of elastic.

Please comment any ideas that you might have! Just keep in mind that

* the .com domain should be free
* the name should not be in use already on the chrome webstore, the firefox webstore or the edge webstore

Thanks!

Ideas so far:
* searchgui
* indexgui
* rubbervue
* rubberlense
* strechyvue
* esvue
* esgui
* esblade
* vuelastic

**Comment by rbouma** [comment]
Maybe SearchGUI? domein is free :) > searchgui.com

**Comment by cars10** [comment]
> Maybe SearchGUI? domein is free :) > searchgui.com
> 
> or http://indexgui.com/

Thanks! I will add these to the list :)

**Comment by mabzzz** [comment]
Hello,

First, I would like to thank you for this beautiful extension. It is very helpful and well made.

We often use the acronym ES when we talk about Elasticsearch.
So, assuming that ES is not a registered trademark of Elasticsearch, what about "esvue" or "esgui" (both .com are availables) ?

**Comment by cars10** [comment]
> First, I would like to thank you for this beautiful extension. It is very helpful and well made.

Thank you! I am glad that you like it.

> So, assuming that ES is not a registered trademark of Elasticsearch, what about "esvue" or "esgui" (both .com are availables) 
?

**Comment by waynetheisinger** [comment]
guilastic

**Comment by waynetheisinger** [comment]
fanlastic

**Comment by TimBaumgart** [comment]
elastigui

**Comment by glicht** [comment]
@cars10 excellent extension. Thanks for building this. I've found it very useful. 

My suggestion: esbrowser

**Comment by lcotonea** [comment]
And what about: esvue?

**Comment by Kraftwurm** [comment]
ESBlade
esblade.com is free right now :)

**Comment by ytvnr** [comment]
Vuelastic ?

**Comment by numeralsix** [comment]
I think all of the above names are great. Vuelastic has a branded feel that stands out more than the others. I really love this tool, btw - it's the first one I reach for when digging into ES.

**Comment by cars10** [comment]
I personally think `vuelastic` sounds great! But i fear that this will lead to the same issue we have right now, because the word "elastic" is still in it

**Comment by KarimTayie** [comment]
esdiscovery
esnavigator

**Comment by LeaderXFX** [comment]
OpenESVue

Now that Elastic's Elasticsearch is no longer open-source, OpenESVue makes a lot of sense if you intend to stick with a logz.io/AWS hard fork.

**Comment by davkap92** [comment]
FlexyUI

**Comment by ez-dev** [comment]
Lots of good ideas here, and let me add **elvue**

**Comment by TimFrHunter** [comment]
Hi, perhaps Elastikvue :)

**Comment by Danistics** [comment]
How about ESpandex ?

**Comment by ytvnr** [comment]
vuetastic search 🌟

**Comment by ytvnr** [comment]
DataStretch
https://media4.giphy.com/media/kEQa33SYt5EIksiqrp/200.gif?cid=5a38a5a2wxc8ly75xexvlswnnfnhbppppfki6zmxvfgtzg74&rid=200.gif&ct=g

**Comment by tony** [comment]
ElasticSeachAdmin (based on PHPMyAdmin)

ElasticSearchDM, EDM, ESDM (based on Redis Desktop Manager, https://rdm.dev/)

esdm.io is available $32.98 a year

**Comment by mahmoudhossam** [comment]
New suggestion: vues, pronounced "views" which is an amalgamation of Vue and ES.

It also avoids the name "elastic" altogether so there's no potential lawsuit for using it.

As for the domain, I'd suggest `vues.app` or `vues.dev` which are currently selling for around €12.54/yr on namecheap as of this writing.

**Comment by totolook** [comment]
> 
> 
>     * ESadmin
> 
>     * ESquirrel
> 
>     * EShell
> 
> 
> Animal metaphore :D

EsBeaver :D

**Comment by Eliak** [comment]
*EShell* sounds good.

What about some words from thefreedictionary.com:
- Elasticity
- Visualiz**es**
- **gui**s**es**
- Namel**es**

**Comment by Brimstedt** [comment]
Vuelas - spanish for "you fly" accoring to google translate
Vuelas.com is not available, but many others

**Comment by ellikamishra** [comment]
Vuesalize

**Comment by MikeV2000** [comment]
Vuelastic ist too close isn't it? ;)

**Comment by MikeV2000** [comment]
Just Vues (pronounced like "views")

**Comment by T100D** [comment]
OpenVue, wit a ;-) to https://opensearch.org/

**Comment by theCuriousOne** [comment]
A couple of attempts for abbreviation based on:
**Browser Extension based on Vue for viewing Elastic(search) Clusters**
BEVES/BEVEC (sounds like - BVk)
Vuebees
BE4ES
Vu4ES
...

**Comment by rharing** [comment]
youknowforsearch-ui or youknowforsearch-client

**Comment by RobertEcker** [comment]
elasvu
elasvue
vuerch

**Comment by CrazyOptimist** [comment]
`es-admin`
(Inspired from `pg-admin`)

**Comment by anandtripathi5** [comment]
`esviewer`
