### ISSUE TITLE
[FEAT] add/remove alias to/from index

### ISSUE THREAD

**Issue by mabzzz** [cars10/elasticvue#38]
**Description**
It would be very useful to be able to:
* add an alias to an index
* remove an alias from an index

**The feature is similar to..**
A similar feature can be found on the chrome extension "elasticsearch-head"
https://chrome.google.com/webstore/detail/elasticsearch-head/ffmkiejjmecolpfloofpjologoblkegm

What do you think ?

**Comment by cars10** [comment]
Sound good! In the meantime you can add and delete aliases by running a query on the "Rest" page. For example to add an alias `mytwitter` to your `twitter` index:

![image](https://user-images.githubusercontent.com/4118628/99905794-5f170d80-2cd3-11eb-97a4-daf436771424.png)

**Comment by mabzzz** [comment]
Yes of course, you are right.
Maybe sometimes I'm just too lazy ^^
Thank you

**Comment by cars10** [comment]
Do you think this will work for you?

![image](https://user-images.githubusercontent.com/4118628/100642553-33ca9900-3339-11eb-88f0-4663f9975dc8.png)
![image](https://user-images.githubusercontent.com/4118628/100642585-3b8a3d80-3339-11eb-887e-d0889e4988af.png)
![image](https://user-images.githubusercontent.com/4118628/100642609-42b14b80-3339-11eb-80ce-9b442c27af3d.png)

**Comment by mabzzz** [comment]
This looks perfect, thank you :100:

**Comment by cars10** [comment]
Implemented in version `0.31.0`. Thanks again for your feedback!

**Comment by mabzzz** [comment]
You are very welcome, thanks again for your work :+1:
