### ISSUE TITLE
[BUG] - Not possbile to run query with _BULK and multiple lines

### ISSUE THREAD

**Issue by ChecksumDK** [cars10/elasticvue#39]
I am trying to run the following valid lines, but the ´"Run Query" button is not available. The query runs fine with other tools. 

POST /cmdb_nodes/_bulk

{ "index" : { "_index" : "cmdb_nodes", "_id" : "xxxx.xxx" } }
{"name": "xxx","system": "zzz","address": "11,4","nodeType": 1,"vendor": "yyy","model": "","manufactored": "1900-01-01T00:00:00","nodePath": "xxxx.xxx","description": "","reference": "","funcLoc": "na","cmdbType": 4,"properties": [],"linkInfo": "","status": 0},

Environment:
* Elasticsearch version: 7.1
* Operating system: Windows server 2019
* Browser + version: Chrome 87.0.4280.66 (Official Build) (64-bit)
* Elasticvue version: 0.30.0
* Running elasticvue as a chrome browser extension:

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/43034297/100327080-114c1f00-2fcb-11eb-97c3-d2394ebc2b0e.png)

**Comment by ChecksumDK** [comment]
Can I test the updated version somehow?

**Comment by cars10** [comment]
Yes! I did not release a new version yet, but you can always build elasticvue on your own. Checkout the [wiki](https://github.com/cars10/elasticvue/wiki/Building-Elasticvue) for instructions.

**Comment by ChecksumDK** [comment]
Don't know if it is a bug, but commented out lines like 
`//lorem ipsum`
causes the query button to be disabled as well.

**Comment by cars10** [comment]
Right now the form checks if your request body is valid json. If it is invalid the button is disabled to prevent you from sending invalid data. Comments are not valid json, so the button is disabled. Maybe i should remove that feature and instead show a warning if invalid json is found :)

**Comment by cars10** [comment]
Implemented in version `0.31.0`. Thanks again for your feedback!
