### ISSUE TITLE
[BUG] Clicking search result item might open previous opened item.

### ISSUE THREAD

**Issue by foqq** [cars10/elasticvue#4]
**Description**
Clicking search result item might open previous opened item.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Opens https://app.elasticvue.com in browser. (Firefox or Chrome)
2. Navigates to SEARCH tab and search for '*'
3. Click the first item then close the popup result dialog.
4. Click the second item.

**Environment (please include the following information):**
* Operating system: macOS
* Browser + version:  Firefox Quantum 66.0.3 (64bit) / Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)
* Elasticvue version: 0.10.0
* How are you running elasticvue? (docker, chrome extension, web app): chrome extension & official web app.

**Comment by cars10** [comment]
Thank you for reporting the issue, fixed in 0.10.1 :)
