### ISSUE TITLE
kibana dev_tools

### ISSUE THREAD

**Issue by yizane** [cars10/elasticvue#40]
**Description**
similar kibana dev_tools

**The feature is similar to..**
Does the feature exist in a similar tool (for example `kibana`)? If so, please:
* /_plugin/kibana/app/kibana#/dev_tools/console
* don't need open kibana to debug console

**Comment by cars10** [comment]
You can run queries on the "Rest" page in elasticvue, just like you can in kibana dev tools :) 
![image](https://user-images.githubusercontent.com/4118628/100602235-eda71280-3303-11eb-8f9d-8f48909cb3cd.png)
