### ISSUE TITLE
[FEAT] Rename cluster

### ISSUE THREAD

**Issue by mahmoudhossam** [cars10/elasticvue#41]
**Description**
Once the cluster is connected to, you can't change the name displayed in the top left corner.

**Comment by cars10** [comment]
Hi, does this work for you?

![image](https://user-images.githubusercontent.com/4118628/100648314-11d51480-3341-11eb-87ab-65c89fa62698.png)
![image](https://user-images.githubusercontent.com/4118628/100648330-18fc2280-3341-11eb-96df-872ecb89368a.png)

**Comment by mahmoudhossam** [comment]
@cars10 Yes it would, thanks for the fast response!

**Comment by cars10** [comment]
Implemented in version `0.31.0`. Thanks again for your feedback!
