### ISSUE TITLE
[BUG] - Having a # in the connection string breaks the interface/plugin

### ISSUE THREAD

**Issue by Aeolun** [cars10/elasticvue#43]
**Description**
Any string with a hash in displays 'invalid url', but I'm not allowed to escape special characters, so having the hash in my password is impossible.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Enter any connection string with # in pass

**Comment by cars10** [comment]
Hey, thanks for reaching out. I am not really happy with the current solution anyway. What do you think about having separate inputs for username, password and host? This should solve this and similar issues.

**Comment by nikhilbaby2000** [comment]
@cars10  Yes, Could you please provide separate fields for `username` & `password`.
Am sure, having special characters in password is common for many configs.

**Comment by cars10** [comment]
I have already implemented this on the `develop` branch, i plan to release a new version in the next few days :)

![image](https://user-images.githubusercontent.com/4118628/105358768-e3640f00-5bf6-11eb-8ee9-d98469070460.png)
![image](https://user-images.githubusercontent.com/4118628/105358792-e959f000-5bf6-11eb-8197-17d8302ced22.png)

**Comment by cars10** [comment]
I just released a new version (`0.32.0`) where this should be fixed. Please let me know if you encounter any issues :)
