### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by zongmi** [cars10/elasticvue#45]
Such a good plug-in, why not support i18n?

**Comment by cars10** [comment]
Hey, thanks for using elasticvue :)

Do you have a specific language in mind? As you already noticed right now there is no i18n support, mostly because it is alot of work. But we can add it of course.

**Comment by zongmi** [comment]
Yes, I am currently using Chinese. This plugin is really good. It is much easier to use than other plugins. If there is Chinese, I would definitely recommend it to my colleagues in the company.

**Comment by zongmi** [comment]
Although I have not participated in an open source project before, if I can, I would like to contribute to the improvement of the plug-in. It gave me the idea to participate.
