### ISSUE TITLE
[FEAT] Possibility to hide system indices  

### ISSUE THREAD

**Issue by milesich** [cars10/elasticvue#50]
**Description**
Indices that start with "." are considered system indices. Would be nice to have an option to hide them from the view. There could be many of them and it is quite annoying to have it mixed with those that I created.

**Comment by cars10** [comment]
Hi, thanks for using elasticvue!

Where exactly do you want to hide system indices? On the `Indices` page?

**Comment by milesich** [comment]
Yes on the `Indices` page because my first page looks like this and it is full of system indices. Ideally if it could be done with a configurable regex so I can hide also those that starts with `apm-*` and keep visible those with `.ds-*` because those are data streams since you don't currently have support for them.

![Screen Shot 2021-03-29 at 09 13 39 AM](https://user-images.githubusercontent.com/1993963/112800354-d4bf2b80-906f-11eb-8232-3d1fcb47f112.png)

**Comment by cars10** [comment]
Sounds useful. I will see what i can do :)

**Comment by cars10** [comment]
Added this feature in `0.34.0`. Let me know if you have any issues :)
