### ISSUE TITLE
Incorrect documents count when mapping is of nested type

### ISSUE THREAD

**Issue by bgrgv** [cars10/elasticvue#54]
**Description**
When documents have nested objects within them, the overall count of the documents in an index is reported inaccurately.

**Steps To Reproduce**
List the steps to reproduce your problem:
Make sure to have an index with few records that have nested objects within it. ("type" : "nested")
1. Open elasticvue
2. Click on `INDICES`
3. Check the count of documents
4. Using Elasticsearch's /_count API, check the number of documents in the index, it'll be different.

**Comment by cars10** [comment]
Please check the output of `docs.count` in `_cat/indices/?v` for your index. This is the number that elasticvue displays in the table

**Comment by cars10** [comment]
So far i am not sure if this is really an issue. Did you manually check the index api? Is the displayed number higher or lower then what you expected?

**Comment by bgrgv** [comment]
I've checked it manually, and the /_count API gives correct number, but Elasticvue reports it differently.

**Comment by cars10** [comment]
Thanks. You are right, `_cat/indices` reports the number of **lucene** documents. The count api `_count` reports the number of **elasticsearch** documents.

Nested objects with `"type": "nested"` behave exactly like a "full" document, so this behaviour might or might not be expected. The only fix for this would be to do an extra request to the `_count` api for each index every time when a user opens the indices page. From a performance standpoint this might be a bit too much, but i will see what i can do :)

**Comment by cars10** [comment]
I have decided to keep this behavior as i think this is expected, because kibana also shows the number of **lucene** documents in the indices table.  But i added a tooltip that explains this.

![image](https://user-images.githubusercontent.com/4118628/128034493-b383e34d-8a12-4d2a-8095-9c371966ab23.png)
