### ISSUE TITLE
[FEAT] Support some graphs (metrics)

### ISSUE THREAD

**Issue by arash-bizcover** [cars10/elasticvue#56]
**Description**
It would be useful to have some graphing and support to show some metrics.

**The feature is similar to..**
It's not that hard to replace Kibana, not so fast but I have faith in you.

**Comment by cars10** [comment]
Please add a concrete example of graphs / metrics that you want to visualize. This is an extremely broad topic :)

**Comment by arash-bizcover** [comment]
ah sorry, I meant just enabling normal graphing capability.
For example, the first basic, most useful would be:

Number(Count) of a specific term in a search. 
e.g.
```
Showing x number of times a doc with source_ip: 1.1.1.1 was indexed per time series.
```

**Comment by cars10** [comment]
Thanks. I will see what i can do, but as explained in #55 this is not a top priority right now.
