### ISSUE TITLE
How can I show support for this amazing tool?

### ISSUE THREAD

**Issue by christopher-caldwell** [cars10/elasticvue#57]
Some devs have a buy me a coffee, some have Patreon. Please let me know how I can show you how great this tool is.

**Comment by cars10** [comment]
Hey, thanks for your support! I will setup something in the next days and report back :)

**Comment by cars10** [comment]
For now i have added a paypal button, i will look into enabling github sponsoring as well. Thanks again!

[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.com/donate?hosted_button_id=65GDZCZTUBVRL)
