### ISSUE TITLE
[BUG] - Chrome extension does not work on brave browser

### ISSUE THREAD

**Issue by harpreetsb** [cars10/elasticvue#61]
Hi,
I recently shifted to brave browser and it looks like the chrome extension does not work on brave browser which is chromium based.

**Comment by cars10** [comment]
Can you give me some more information please? What exactly does not work? Installing the extension? Running it? What error message do you see?

**Comment by harpreetsb** [comment]
I am so sorry,
Plugin installs fine. The tab to view indices does not show anything.
I checked in developer tools. The json response seems to be valid

**Comment by cars10** [comment]
Works just fine for me. Have you tried

* Restarting your browser
* Reconnecting to your cluster (Click "Disconnect and reset" in the footer)

Are there any errors in the browser console?

![image](https://user-images.githubusercontent.com/4118628/128035343-27967de6-7f7d-437c-ab75-31c0418accff.png)
![image](https://user-images.githubusercontent.com/4118628/128035372-9690b3e1-0cb2-4f69-a6e1-05a2489c62a1.png)

**Comment by harpreetsb** [comment]
restarted browser still does not work
![image](https://user-images.githubusercontent.com/6584304/128121213-7c00e10e-30e6-4182-963b-12b055ab25c1.png)
error in console
![image](https://user-images.githubusercontent.com/6584304/128121293-f404c541-4999-4a96-b6aa-09c6128d8d6d.png)
![image](https://user-images.githubusercontent.com/6584304/128121353-70e5534d-5927-4afd-af65-002e5c17a8bc.png)

**Comment by cars10** [comment]
Hm,  thats weird. What OS are you using? Do you have other addons installed?

**Comment by harpreetsb** [comment]
Just a password manager

**Comment by cars10** [comment]
I have release a new version of elasticvue (`0.36.1`), can you update the extension and check if you still have any issues?

**Comment by harpreetsb** [comment]
:/ same error
I am on ubuntu 20.04
![image](https://user-images.githubusercontent.com/6584304/129308913-f03159f9-8061-43c3-9989-2d402b8752ec.png)

**Comment by cars10** [comment]
Thanks for trying again! I can finally reproduce this but only on ubuntu. Works on manjar & arch... Quite weird, but i will look into this now as i can finally try to fix it.

**Comment by harpreetsb** [comment]
Nice, sorry I didnot mention the OS earlier.
But this works well with Firefox on Ubuntu and Google Chrome on Ubuntu.
I recently shifted to brave as my primary browser and would like to stay on it.

**Comment by cars10** [comment]
Should be fixed in `0.36.3`, thanks for reporting this issue!
