### ISSUE TITLE
[BUG] - Has no body in POST requests on REST tab.

### ISSUE THREAD

**Issue by Eliak** [cars10/elasticvue#65]
**Description**
REST tab sends POST requests without body.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on REST tab
3. Set "HTTP Method" value "POST"
4. Set "Path" value "_search"
5. Set request body value '{"query": {"match_none":{}}}'
6. Click on "SEND REQUEST" button
7. There are all documents of elasticsearch in the resonse
8. Chrome DevTools doesn't show "Request Payload" tab

**Screenshots**
![image](https://user-images.githubusercontent.com/3325838/129334014-eeaf9219-08ac-448a-bacf-2d98615980c9.png)

**Environment (please include the following information):**
* Elasticsearch version: 7.5
* Operating system: Linux
* Browser + version: Chrome 92.0.4515.107
* Elasticvue version: 0.36.1

**Comment by cars10** [comment]
Thanks! No idea how i did not notice that during testing. Fixed, `0.36.2` will be released soon!
