### ISSUE TITLE
[FEAT] Read Only Mode

### ISSUE THREAD

**Issue by Xhanti** [cars10/elasticvue#67]
**Description**
Can the extension be made readonly? I.E remove all functionality that modifies the ES cluster.

**The feature is similar to..**
N/A

**Additional context**
I enjoy using the tool and it is very helpful. But we can not point it at the live cluster, as someone might accidentally hit the delete all indices button and cause a production outage. If there was a way to disable the utilities that modify the cluster, then I could motivate for using this great extension in more than just our dev cluster.
Regards

**Comment by cars10** [comment]
Hey, thanks for using elasticvue! 
Why don't you simply use a readonly user for accessing your cluster? Elasticsearch provides many built-in roles, the `viewer` role for example grants readonly access to the whole cluster. See https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-roles.html

I could add a flag for some kind of readonly mode, but you could still send REST requests to delete and modify data, so im not sure that this is the right approach.

**Comment by Xhanti** [comment]
Hi, 
Thank you for the prompt response. We are using an older version (5.6.0) and they had not yet rolled out that feature. It also looks like an xpack feature, we don't use xpack in our setup. I take your point though, that they can still post malicious requests to the cluster, the extensions would be giving us a false sense of security with a flag. I'll close this issue, I'll have to come up with something else. 
Thank you for the assistance

**Comment by cars10** [comment]
Alright :) BTW, Elasticsearch 5.6 has been [EOL](https://www.elastic.co/de/support/eol) for 2 years now. You might consider upgrading for security reasons.

**Comment by Xhanti** [comment]
We are desperately trying to upgrade, a few issue have prevented us. 
But we are on it. 
Thank you for the kind consideration

**Comment by axilis-marko** [comment]
> It also looks like an xpack feature, we don't use xpack in our setup.

To add to this. When browsing through a new tool, I feel more comfortable having a read-only option. That way I'm more free to click around while getting familiar with it.
