### ISSUE TITLE
[BUG] Switching between index pattern and index selection does not work correctly

### ISSUE THREAD

**Issue by cars10** [cars10/elasticvue#7]
**Description**
Switching between index pattern and index selection does not work correctly, the search form always uses the wrong value to search.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Go to search
3. Enter an index pattern
4. Click on "or select indices"
5. Click on "search"
6. Now the index pattern is still active and not the empty index selection

**Environment (please include the following information):**
* Operating system: Manjaro
* Browser + version: Chrome 76
* Elasticvue version: 0.11.0
* How are you running elasticvue? (docker, chrome extension, web app): Dev

**Comment by georgeyeint** [comment]
In "Search" menu, when you fill "Filter" input all good, but then you change search query or index type - "Filter" input value still the same and result is empty.
First time, I thought that query is not worked.
May be clean filter value on new search or mark it by a red color to see that result was filtered out.
Or change event "Nothing found." to "Found 1000 items. Filtered to 0" or something else.

**Comment by cars10** [comment]
Thank you, great idea :) I will change the text if nothing was found because of an existing filter.

But i am not sure if cleaning the value would be the way to go - imagine you are filtering logs and going through them one index at a time. Would be quite annoying to have to reender your filter every time you select a new index.

**Comment by georgeyeint** [comment]
agree.
"deleting data" is worse than only "inform" user.
thanks for great app!
