### ISSUE TITLE
Filter multiple fields by key

### ISSUE THREAD

**Issue by ZHANG-GXJ** [cars10/elasticvue#70]
**Description**
I'm not sure if elasticvue support how to filter the result by key.
**The feature is similar to..**
As in elasticsearch head, I can easily filter result by the key of field.
* link the tool
* explain how/where to use the feature
* if applicable, add screenshots to help explain the feature 

**Additional context**
Anything else?

**Comment by cars10** [comment]
Hi, you can customize the search query however you like. Some examples to query multiple fields:

Using a bool query
```
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "author_name": "Edgar"
          }
        },
        {
          "match": {
            "message": "Geology"
          }
        }
      ]
    }
  },
  "size": 10,
  "from": 0,
  "sort": []
}
```

Using a multi-match query
```
{
  "query": {
    "multi_match": {
      "query": "Geology",
      "fields": [
        "author_name",
        "message"
      ]
    }
  },
  "size": 10,
  "from": 0,
  "sort": []
}
```

![1](https://user-images.githubusercontent.com/4118628/133268905-9ba9f903-7f9f-4cba-bdf6-1aa3b43fc2f3.png)
![2](https://user-images.githubusercontent.com/4118628/133268917-a1e11cc9-6ed4-4367-9a43-df0316a2a37a.png)
