### ISSUE TITLE
[FEAT] Add cluster by GET instead of POST request

### ISSUE THREAD

**Issue by FallDi** [cars10/elasticvue#71]
**Description**
We configure elastic in readonly mode, in such case only GET & HEAD requests allowed. However during add cluster POST request executed. 
```
POST http://IP:9200/_search
```

Is it possible to make `GET http://192.168.34.37:9200/_search` in such case? GET also respond with data.

**Additional context**
<img width="961" alt="Screenshot 2021-09-25 at 13 20 18" src="https://user-images.githubusercontent.com/4299295/134761083-26981f39-7500-44b2-a4df-82cfb4eadde5.png">

**Comment by cars10** [comment]
Hey @FallDi , thanks for using elasticvue :) I see that this is an issue if you are using read-only roles.

Changing the  test `_search` query during setup to `GET` will not be enough in this case because i also use POST for the Search page. I will try to change this to make read-only roles usable.

**Comment by cars10** [comment]
Can you tell me a bit more about how you configured your cluster? As far as i am aware there is no way to only enable GET & HEAD requests in elasticsearch. Do you use a reverse proxy that denies all other requests? Is there a specific reason to not use elasticsearch roles to achieve this?

**Comment by FallDi** [comment]
Yep, it was disable on proxy level :) Looks like we restrict POST/PUT by mistake. We just would like to disable data delete. 
Now it solved by DELETE restriction. With GET/HEAD/POST/PUT elasticvue works like a charm :)
