### ISSUE TITLE
[FEAT] Add shards allocation overview

### ISSUE THREAD

**Issue by txxa** [cars10/elasticvue#72]
**Description**
It would be quite helpful to have an overview on how the shards are allocated to the nodes.

**The feature is similar to..**
Does the feature exist in a similar tool (for example `kibana`)? If so, please:
* link the tool
[elasticsearch-head](https://github.com/mobz/elasticsearch-head), [cerebro](https://github.com/lmenezes/cerebro)
* explain how/where to use the feature
I suggest to add a new tab called "Shards" to the top menu
* if applicable, add screenshots to help explain the feature 
Example from cerebro:
![image](https://user-images.githubusercontent.com/32124408/134863237-35c89b61-e093-4846-986a-b55d29ff6f6b.png)

**Additional context**
Beside the visualization of the shards it would also be helpful to have the possibility to relocate the shards.

**Comment by cars10** [comment]
Hey @txxa , thanks for using elasticvue :)
Can you tell me a bit more about your use-case here? Do you really need this "complete" overview or are you looking for something more specific, for example:

- Per node: see which inidices use the shards on node X
- Per index: see on which nodes&shards your index X is located
- or something else?

I personally think that the overview from cerebro is a bit "too much" as it shows not much information but uses a bit amount of space.

**Comment by txxa** [comment]
Hi @cars10, thanks for providing elasticvue :)

Basically what I would like to see is how the shards are allocated, meaning which shards of what index are allocated to which node. Also to see unassigned shards of the indices.
A nice to have would then be to have the possibility to assign unassigned shards by clicking on them.

Therefore I really like a table, it is simple to understand and provides a good overview.
Something like:

| | index1 | index2 | index3 |
| --------------- | --------------- | --------------- | --------------- |
| unassigned | [3] | [3] |  |
| node1 | **[0]** **[1]** _[2]_ _[3]_ | **[0]** _[1]_ **[2]** _[3]_ | _[0]_ **[1]** **[2]** |
| node2 | _[0]_ **[1]** **[2]** _[3]_ | _[0]_ **[1]** **[2]** _[3]_ | **[0]** _[1]_ **[2]** |
| node3 | **[0]** _[1]_ **[2]** _[3]_ | **[0]** **[1]** _[2]_ _[3]_ | **[0]** **[1]** _[2]_ |

**Comment by cars10** [comment]
![image](https://user-images.githubusercontent.com/4118628/147860965-6374b6de-c3e2-4933-becf-1e893bb00157.png)

Something like this will be included in the next release. You can select and relocate shards.

**Comment by cars10** [comment]
Fixed in `0.37.0`
