### ISSUE TITLE
[FEAT/BUG] Allow using an SSL cert to avoid CORS HTTP errors

### ISSUE THREAD

**Issue by mattjanssen** [cars10/elasticvue#73]
**Description**
We currently use URLs like http://localhost:8080 or http://dev-domain.com:8080 to access Elasticvue. That works just great until you're in the newest Chrome and trying to connect to an AWS-hosted Elastic on HTTPS. This is when we run into CORS HTTP errors.

Could we supply a domain name and SSL certificate in the Docker config and thus enable HTTPS connections to Elasticvue?

![image](https://user-images.githubusercontent.com/745319/136423986-2d313992-f920-4e70-9c0f-52c61aba2713.png)

```
indices:1 Access to fetch at 'https://xxxxx.eu-central-1.es.amazonaws.com/myindex' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
app.95d5d16b.js:1 GET https://xxxxx.eu-central-1.es.amazonaws.com/myindex net::ERR_FAILED
```

**Comment by cars10** [comment]
> Sadly on AWS I can't change the http.cors.allow-origin setting.

I am pretty sure that you can change every setting of elasticsearch in aws.

> Solution found: I used your amazing Elasticvue Chrome extension! smiley

Alright, great that you found a solution :)
