### ISSUE TITLE
about scroll bar

### ISSUE THREAD

**Issue by bewareilive** [cars10/elasticvue#75]
I would like you to adjust the height of the table so as to eliminate the double scroll bar

**Comment by cars10** [comment]
You are right, table height can be suboptimal right now. Will include this in the next version. Thanks!

**Comment by bewareilive** [comment]
> You are right, table height can be suboptimal right now. Will include this in the next version. Thanks!

When the table show >=20 indexes,I saw double scroll bar again 😭😭😭😭😭😭😭

**Comment by cars10** [comment]
The double scroll bar is not a bug, its a feature. The idea is that you have a fixed header in the table so you can always see the table headers, no matter how many entries you are seeing. But the table height should still be adjustable as i said :) This feature is still on my list, sorry its taking so long right now.

**Comment by bewareilive** [comment]
> The double scroll bar is not a bug, its a feature. The idea is that you have a fixed header in the table so you can always see the table headers, no matter how many entries you are seeing. But the table height should still be adjustable as i said :) This feature is still on my list, sorry its taking so long right now.

The index table is in"/html/body/div/div/main/div/div/div/div[2]/div/div[2]/div[1]"   
css is 
.table--fixed-header .v-data-table__wrapper {
    max-height: 800px;
    overflow-y: auto;
    height: 100%;
}
disable max-height is OK.  so set v-data-table [height]  May be able to solve
