### ISSUE TITLE
[FEATURE] Support arm64

### ISSUE THREAD

**Issue by mikart143** [cars10/elasticvue#76]
Hello!
I would like to suggests to introduce arm64 support.
I checked Dockerfile and all the images seems to support the arm64 architecture but looking at the docker hub none of the images seems to support this. Are there any problems with this ?

**Comment by cars10** [comment]
No known issues, i just never tried it. Guess I could test in on a raspberry pi :)

**Comment by mikart143** [comment]
@cars10 I can try it too on a laptop if you wish. If it is just a matter of running root docker file

**Comment by mikart143** [comment]
@cars10 Unfortunately no luck. There is problem with puppeteer npm package the best issue to track is: puppeteer/puppeteer#7740

**Comment by mikart143** [comment]
@cars10 I made this working on apple m1, I will make pr

**Comment by t3chn0m4g3** [comment]
Any progress on this?
Can offer my help for testing.

**Comment by cars10** [comment]
Sorry for the delay, covid hit. I am about to release `v0.37.0` in the next few days. This feature is planned for the version after that, `0.38.0`.

**Comment by t3chn0m4g3** [comment]
Thank you for the swift feedback!
Offer to support testing stands, just ping me.

**Comment by cars10** [comment]
Version `0.39.0` was published with docker images for `amd64`, `arm64` and `arm/v7`. Please let me know if you have any issues with these :)

**Comment by t3chn0m4g3** [comment]
Awesome! Thank you!
