### ISSUE TITLE
[FEAT]Please add batch delete index function 

### ISSUE THREAD

**Issue by nomatterfine** [cars10/elasticvue#78]
Please add batch delete index function 。
3q！

**Comment by nomatterfine** [comment]
Check box

**Comment by cars10** [comment]
Will be included in the next version `0.37.0`.

![image](https://user-images.githubusercontent.com/4118628/141659888-3db0374b-ebf8-424a-a3d0-4224576fe098.png)
![image](https://user-images.githubusercontent.com/4118628/141659895-206ae17d-f0a1-4e14-a0bc-ab12a63c2336.png)

**Comment by nomatterfine** [comment]
Nice job
