### ISSUE TITLE
When the index page of the page is refreshed multiple times, the documents will start to increase, and the number of documents will not be read after a while, and it will not move, but the documents in kibana will increase. 

### ISSUE THREAD

**Issue by nomatterfine** [cars10/elasticvue#80]
When the index page of the page is refreshed multiple times, the documents will start to increase, and the number of documents will not be read after a while, and it will not move, but the documents in kibana will increase. 

Elasticvue 0.36.4

![image](https://user-images.githubusercontent.com/90117583/141227662-73c3486b-8b7a-4f3f-aef1-2ea0e7a7ba30.png)

**Comment by cars10** [comment]
Are you 100% sure that you where looking at the same index? Elasticvue does not cache these results. The indices are loaded on each pageload / refesh.

Maybe your elasticsearch cluster was still ingesting documents?

BTW, you can enable automatic reload so you do not have to refresh the page manually:
![image](https://user-images.githubusercontent.com/4118628/141276205-68fbfc5a-0cd0-40ec-b2cf-52c98bdcb613.png)

**Comment by nomatterfine** [comment]
I tried it your way, and it turned out to be normal! Thanks!

**Comment by cars10** [comment]
Great! Let me know if you face this issue (or a different one) again.
