### ISSUE TITLE
[BUG] - cluster selection is propagated to all elasticvue tabs

### ISSUE THREAD

**Issue by bodenr** [cars10/elasticvue#81]
**Description**
The current active cluster in elasticvue has recently start propagating to all elasticvue tabs. As a result I can no longer view multiple clusters, and moreover the current active cluster can change from "under me" which can lead to operating on a cluster I didn't intend to.

Note: I've been using elasticvue for months and this never happened before; just started occurring in the last few days.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue tab to cluster1
2. Open another elasticvue tab (or browser window) and select cluster2
3. Refresh the first tab (cluster1)... now the first tab is set to cluster2 automatically (e.g. sync'd between the tabs)
4. I have no way to view multiple clusters at the same time (via different tabs/windows)

**Environment (please include the following information):**
- ubuntu 20.x
- chrome Version 96.0.4664.45 (Official Build) (64-bit)
- Elasticvue 0.36.4 via web app extension for chrome
- it also happens on mac os with chrome Version 96.0.4664.55 (Official Build) (x86_64)

**Comment by T100D** [comment]
This could because chome suses the same cache directory for all browser Windows. Because of that we start chromium in sepoerate Windows with sepoerate directories.

**Comment by cars10** [comment]
Hey, thanks for using elasticvue :)

> Note: I've been using elasticvue for months and this never happened before; just started occurring in the last few days.

Are you sure about that? Based on how vuex and vuex-persisted-state work this should not be new behavior. But i agree that this is a very valid usecase and should be adressed in a future version.

**Comment by bodenr** [comment]
@cars10 I'm sure that I used to be able to have connections to different clusters in the same browser (different tabs/windows), but I'm not sure when it stopped working.

FYI -- I just installed elasticvue in FireFox and confirmed the same behavior; state is sync'd between tabs.

**Comment by cars10** [comment]
Okay, thanks for the quick reply :)

I am currently thinking about how this should behave. What would you expect in the following situations?

1. One window of elasticvue is currently open. You open a new tab of elasticvue (by right-click a link and selecting "open in new tab" or clicking the extension button in the toolbar again). What happens in the new tab? Is the "default"/first cluster active? Do you see a cluster selection prompt? Is the "previous" cluster currently selected? What even is the "previous" cluster?
2. Two windows of elasticvue are currently open, each with different clusters selected. You open a new tab of elasticvue. What happens in the new tab? Which cluster is active?
3. Apart from the behavior when opening a new tab. Do you think a functionality to quickly open a cluster in a new tab is useful? For example like this (quick mockup, not actual functionality): 
![image](https://user-images.githubusercontent.com/4118628/144918578-a6a94433-acf0-4370-8926-54c99c833f0b.png)

**Comment by bodenr** [comment]
thanks for the quick response!

i'd keep it simple; when opening a new tab the behavior is the same as today. the main thing for me is the ability to work with more than 1 cluster at a time and not be forced to only have a single cluster open across all tabs/windows (e.g. sync'd).

i'd likely use the "open in tab" option, but certainly not necessary.

**Comment by cars10** [comment]
Hey @bodenr , for the next release i will save the currently active cluster in the sessionStorage. This change allows you to have different active clusters per tab. 

This is still not perfect though: Any data that is saved by elasticvue (e.g. the rest history) is still shared between all clusters. The correct solution would be to have a separate storage *per* cluster. This is planned for a future version of elasticvue.

**Comment by bodenr** [comment]
@cars10 sorry for the delayed response.
thank you so much for taking the time to consider and implement this; i sincerely do appreciate it!

**Comment by cars10** [comment]
Fixed in `0.37.0`
