### ISSUE TITLE
[BUG] - Your path.repo setting is not setup correctly even thou when it's set

### ISSUE THREAD

**Issue by fm4tt0s** [cars10/elasticvue#83]
**Description**
getting **'Your path.repo setting is not setup correctly.'** even though value is set in elasticsearch.yml 

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on **Snapshots** or **Repositories**
3. Get **Your path.repo setting is not setup correctly.**

**Screenshots**

**Environment (please include the following information):**
* Elasticsearch version: 2.3
* Operating system: RHEL/running ES under docker
* Browser + version: Chrome Version 96.0.4664.110
* Elasticvue version: 0.36.4
* How are you running elasticvue? (docker, browser extension, web app): browser extension

**Additional context**

I'm pretty aware that ES version is quite old, but it's a huge corp appl and there's a lot too coordinate to upgrade it, and the appl is actually being decoupled into minor pieces and it's probably going to be decomm by 3q22, until then...

```
cat elasticsearch.yml
network.host: 0.0.0.0
path.repo: /snapshots
```

**Comment by cars10** [comment]
Hi, thanks for reporting this issue. I will try to reproduce it, but i cannot promise a fix. Elasticvue aims to support the two latest major versions of elasticsearch and 2.3 is sadly not one these. But i will see what i can do :)

**Comment by cars10** [comment]
Hey @fm4tt0s , i can reproduce this issue. Elasticvue uses the `_cluster/settings` endpoint to query the `path.repo` setting, sadly elasticsearch 2.x does not include this setting in the response. As far as i can tell there is no way for me to check if the `path.repo` setting is setup correctly on older elasticsearch versions.

But i will adjust the warning to make it less confusing that encounter this issue.

**Comment by fm4tt0s** [comment]
much appreciated @cars10

**Comment by stephanediondev** [comment]
Hi @cars10 

Maybe you can check in node settings with request to `_nodes` or directly with master node if you have it `_nodes/xxx`

In this response you have foreach node an array with settings

You can check the `path` key if `repo` value is defined

![image](https://user-images.githubusercontent.com/528192/147572479-827a5947-6f9e-4ff2-b293-a027458e87fd.png)
