### ISSUE TITLE
[FEAT] Save queries and name them

### ISSUE THREAD

**Issue by enyosolutions** [cars10/elasticvue#84]
**Description**
It would be great to have a way to save queries. 
The rest section has some history but it's hard to remember a query you wrote few weeks ago.
Something like the history but with to possibility to save them with some name would be awesome...
**The feature is similar to..**
- postman
- insomnia

**Additional context**

**Comment by cars10** [comment]
Hi, is the rest history in combination with favorites not enough for you? You can filter the url to find the queries.

**Comment by cars10** [comment]
Closed due to inactivity. Please reopen if the rest history does not work for you.

**Comment by enyosolutions** [comment]
Hello sorry first message did not reach me. I have problem is if you have 20 different queries that address the test index how you know which one is the right one

**Comment by enyosolutions** [comment]
@cars10
