### ISSUE TITLE
[BUG] - Elasticsearch v7 need to use `track-total-hits` to return the correct total count

### ISSUE THREAD

**Issue by xiaobeicn** [cars10/elasticvue#85]
## reference
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-your-data.html#track-total-hits

**Comment by cars10** [comment]
Hi, can you please explain this issue in more detail? Are you aware that you can always edit the search query manually to include any options you like?

**Comment by xiaobeicn** [comment]
I'm aware of custom search, but if the total number is more than 10,000, the statistics will always show up as 10,000 in the search results

The default search query
```json
{
  "query": {
    "query_string": {
      "query": "*"
    }
  },
  "size": 10,
  "from": 0,
  "sort": []
}
```
It needs to be added for V7 `track_total_hits` 
```json
{
  "query": {
    "query_string": {
      "query": "*"
    }
  },
  "size": 10,
  "from": 0,
  "sort": [],
  "track_total_hits": true
}
```

**Comment by cars10** [comment]
`track_total_hits` does have performance implications though. But you are right, i think searching in elasticvue is not really performance critical, so i will add `track_total_hits` to the default query for now. Might be removed in the future if it causes trouble for some users, then you would have to add it manually to your search queries.

**Comment by cars10** [comment]
@xiaobeicn it seems like i have to revert this, sorry. `track_total_hits` is not supported on elasticsearch `2.x` up to at least `5.x` so this causes issues for many users. see #90
