### ISSUE TITLE
[FEAT] possibility to save a query

### ISSUE THREAD

**Issue by enyosolutions** [cars10/elasticvue#88]
Follow up on this https://github.com/cars10/elasticvue/issues/84
**Description**
It would be great to have a way to save queries.
The rest section has some history but it's hard to remember a query you wrote few weeks ago.
Something like the history but with to possibility to save them with some name would be awesome...

- A simple and quick solution would be to be able to edit a history request and add a name to the request.
- A better one would be to have a button for saving 

**The feature is similar to..**
postman
insomnia
**Additional context**

I have various queries for various elastic search servers : in an index containing offers, i have about 10 differents queries that i run 
- active offers
- inactive offers
- related to a certain client
- offers not updated for one week
- number of offers by client
- offers by country
- ordered by most clicked offers 
- ordered by least clicked offers 

Using the bookmark feature those would all appear under the name of the index...

**Comment by cars10** [comment]
This will be implemented in the upcoming 1.0 beta.
