### ISSUE TITLE
[BUG] - Error in request on shards overview page

### ISSUE THREAD

**Issue by sayeui** [cars10/elasticvue#92]
**Description**
When there are too many indexes, a request error occurs when opening the shards overview page. The reason may be that you spliced all the indexes directly on the URL of the GET request, resulting in the URL being too large.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on Shards 
3. wait

**Screenshots**
![image](https://user-images.githubusercontent.com/49316381/153394749-e74c9c55-cec3-4711-a895-60e7c48d7390.png)
![image](https://user-images.githubusercontent.com/49316381/153395098-3376571c-fad4-40f1-ba60-dca8cce0dfbd.png)

**Environment (please include the following information):**
* Elasticsearch version:  6.1.1
* Operating system: Windows 10
* Browser + version:  Google Chrome 96.0.4664.93
* Elasticvue version: 0.38.0
* How are you running elasticvue? (docker, browser extension, web app): browser extension

**Comment by cars10** [comment]
Hey, thanks for using elasticvue. How many indices do you have in total?

**Comment by sayeui** [comment]
As the first screenshot shows, the number of indexes is over 3000, there are about 3026, and it may grow.
And thanks for developing such a great app.  :D

**Comment by sayeui** [comment]
> Hey, thanks for using elasticvue. How many indices do you have in total?

Sorry, I may have forgotten to select a reply, so maybe you didn't see my previous reply in time. :P

**Comment by cars10** [comment]
I got your reply and i can reproduce the issue. Still working on a fix though :) Need to rewrite the shards page.

**Comment by sayeui** [comment]
> I got your reply and i can reproduce the issue. Still working on a fix though :) Need to rewrite the shards page.

So glad to have helped with the project and thanks again for your work! :D
