### ISSUE TITLE
[BUG] - Elasticsearch version not updated in header

### ISSUE THREAD

**Issue by mabzzz** [cars10/elasticvue#94]
**Description**
After upgrading Elasticsearch, the version number displayed in the header (cluster selector) is not updated.
However, the version number displayed on the homepage is correctly updated.
It's not a big issue but it can be misleading. Anyway, thanks for the great job !

**Steps To Reproduce**
1. Add a new cluster to elasticvue
2. Check Elasticsearch version number displayed in the header (cluster selector)
3. Upgrade Elasticsearch
4. Refresh elasticvue
5. Check Elasticsearch version number displayed in the header (cluster selector) => still show previous version number

**Environment (please include the following information):**
* Elasticsearch version: upgrading from 6.5.4 to 7.17.0
* Operating system: Linux (Ubuntu 21.10)
* Browser + version: Firefox 97.0
* Elasticvue version: 0.38.0
* How are you running elasticvue? (docker, browser extension, web app): browser extension

**Comment by cars10** [comment]
Thanks! Will be fixed in the next version.

**Comment by cars10** [comment]
Fixed in `0.39.0`
