### ISSUE TITLE
[BUG] - Search items redirect to wrong cluser details

### ISSUE THREAD

**Issue by SamithPerera** [cars10/elasticvue#98]
I'm using elastic vue for monitor multiple Elasticsearch clusters.  when I search for specific cluster it's showing the correct outputs, but once I click on the item it's redirecting to a different cluster detail page

**Comment by cars10** [comment]
Do you open the page in a new tab?

**Comment by cars10** [comment]
Closed because i cannot reproduce this issue. Please re-open with more details if the issue persists :)
