### ISSUE TITLE
[BUG] - Search results not showing

### ISSUE THREAD

**Issue by KoalaBear84** [cars10/elasticvue#99]
**Description**
Search results not showing because it's on page X and there are no results for page X.

Many times I do some tests and think that my query is wrong / not showing results, but it should. And it looks like it never resets to the first page when pressing search.

So then I'm checking what is wrong with my query, as it should have matching records. But in the first two weeks I just stopped because I couldn't get it working.

It should always reset the page so it will display the expected results when searching, at least by default.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Search for something
3. Go to page 5 (ex.)
4. Search something else with less than 50 results
5. Nothing is showing up

**Environment (please include the following information):**
* Elasticsearch version: 7.17
* Operating system: Docker
* Browser + version: Edge newest
* Elasticvue version: 0.39.0
* How are you running elasticvue? (docker, browser extension, web app):
Official web app

**Comment by cars10** [comment]
Hey, thanks for using elasticvue. You are 100% correct, the page should reset when you do a new search.

**Comment by KoalaBear84** [comment]
Thanks! 👍
